import type { MessageSchema } from './index';

const messages: MessageSchema = {
  brewfile: {
    installTitle: 'Install apps from My List',
    title: 'My list',
    description:
      'Save apps for later, then install them together or export a Brewfile. This list stays on this device.',
    count: '{count} item | {count} items',
    emptyTitle: 'Your list is empty',
    emptyDescription: 'Choose “Add to My List” on an app’s details page or in an installed app’s menu.',
    browse: 'Discover Apps',
    fileTitle: 'Generated by OpenNavo',
    download: 'Export Brewfile',
    moveUp: 'Move {name} up',
    moveDown: 'Move {name} down',
    remove: 'Remove {name} from the list',
    add: 'Add to My List',
    inList: 'In My List',
    removeShort: 'Remove from My List',
    added: 'Added to My List',
    full: 'Your list is full (200 apps). Remove an app first.',
    saveFailed: 'Unable to save or read your list. Check local storage and try again.',
    install: 'Install {count} apps',
    installHint: 'Installed, queued and unavailable apps are skipped.',
    copy: 'Copy Brewfile',
    exported: 'Brewfile exported'
  },
  app: {
    name: 'OpenNavo'
  },
  nav: {
    browse: 'Browse',
    lists: 'Lists',
    mine: 'Library',
    discover: 'Discover',
    categories: 'Categories',
    rankings: 'Rankings',
    installed: 'Installed',
    updates: 'Updates',
    history: 'History',
    settings: 'Settings',
    updatesBadge: '{count} update available | {count} updates available'
  },
  env: {
    label: 'Homebrew',
    checking: 'Checking…',
    checkingHint: 'Reading the Homebrew setup on this Mac',
    ready: 'Homebrew is ready',
    noBrew: 'Homebrew not installed',
    noBrewHint: 'Click to install',
    version: '{version} · {arch}',
    mirrors: {
      official: 'Official source',
      tuna: 'TUNA mirror (Tsinghua)',
      ustc: 'USTC mirror',
      aliyun: 'Alibaba Cloud mirror'
    }
  },
  toolbar: {
    back: 'Back',
    forward: 'Forward',
    search: 'Search {count} app | Search {count} apps',
    searchShort: 'Search apps',
    taskRunning: '{action} {name}',
    taskQueued: '{count} more queued | {count} more queued'
  },
  rail: {
    title: 'Overview',
    subtitle: 'Homebrew on this Mac',
    installed: 'Installed',
    updates: 'Updates',
    updatesHint: 'About {size} to download',
    updatesNone: 'Everything is up to date',
    disk: 'Disk usage',
    diskHint: '{size} in cache',
    lastCheck: 'Last check',
    lastCheckAuto: 'Daily at {time}',
    lastCheckManual: 'Automatic checks are off',
    never: 'Not checked yet',
    weeklyTop: 'Trending',
    weeklyTopHint: 'App installs in the last 30 days'
  },
  common: {
    empty: 'No content yet',
    refreshFailed: 'Some content could not be loaded. Previously loaded content has been kept.',
    notFound: 'This content is unavailable or has been removed',
    loadMore: 'Load More',
    viewAll: 'See All',
    viewRankings: 'See Rankings',
    retry: 'Retry',
    loading: 'Loading…',
    more: 'More actions',
    copy: 'Copy',
    copied: 'Copied',
    cancel: 'Cancel',
    close: 'Close',
    count: '{count} app | {count} apps'
  },
  offline: {
    title: 'Can’t reach the OpenNavo service',
    description: 'Showing the local catalog. Screenshots, release notes and collections need a connection.'
  },
  discover: {
    featured: 'Featured This Week',
    viewDetails: 'View Details',
    allCategories: 'All',
    categoriesLabel: 'Categories',
    popularApps: 'Popular Apps',
    popularAppsHint: 'Homebrew installs in the last 30 days',
    recentlyUpdated: 'Recently Updated',
    recentlyUpdatedHint: 'Apps with new releases',
    collections: 'Collections',
    installCollection: 'Install Collection',
    collectionCount: '{title} · {count} app | {title} · {count} apps'
  },
  categories: {
    title: 'Categories',
    subtitle: '{count} category to browse by purpose | {count} categories to browse by purpose',
    packages: '{count} app | {count} apps',
    empty: 'Nothing in this category yet',
    sortLabel: 'Sort',
    sorts: {
      popular: 'Popular',
      updated: 'Recently Updated',
      name: 'Name'
    }
  },
  rankings: {
    title: 'Rankings',
    subtitle: 'Based on official Homebrew install statistics, updated daily',
    periodLabel: 'Period',
    periods: {
      installs30d: '30 days',
      installs90d: '90 days',
      installs365d: '1 year'
    },
    noStats: 'No data yet'
  },
  search: {
    title: 'Search',
    results: '{count} result for “{q}” | {count} results for “{q}”',
    empty: 'No results for “{q}”',
    emptyHint: 'Try another keyword, the English name or a pinyin abbreviation',
    alias: 'Also known as {name}',
    prompt: 'Type a name, a purpose or a command to search'
  },
  collections: {
    title: 'Collections',
    subtitle: 'Curated sets of apps you can install in one go',
    empty: 'No collections yet',
    items: '{count} app | {count} apps',
    install: 'Install Collection',
    installTitle: 'Install “{title}”',
    installDescription:
      '{count} package will be installed one by one. Installed ones are skipped. | {count} packages will be installed one by one. Installed ones are skipped.',
    installConfirm: 'Install',
    allInstalled: 'Everything in this collection is installed',
    installed: 'Installed',
    queued: '{count} added to the queue | {count} added to the queue',
    offline: 'Collections need a connection'
  },
  package: {
    arch: {
      arm64: 'Apple silicon',
      x86_64: 'Intel'
    },
    autoUpdates: 'Auto-updates',
    disabled: 'Disabled',
    deprecated: 'Deprecated',
    homepage: 'Homepage',
    fromTap: 'From',
    stats: {
      label: 'Stats',
      installs30d: '30-day installs',
      rank: '#{rank} in {kind}',
      installs365d: '1-year installs',
      total365: 'Last 365 days',
      latest: 'Latest version',
      size: 'Download size',
      cadence: 'Release cadence',
      releases30d: '{count} release in 30 days | {count} releases in 30 days'
    },
    cadence: {
      daily: 'Daily',
      weekly: 'Weekly',
      biweekly: 'Every 2 weeks',
      monthly: 'Monthly',
      irregular: 'Irregular'
    },
    tabs: {
      label: 'Package tabs',
      overview: 'Overview',
      versions: 'Release Notes',
      dependencies: 'Dependencies',
      details: 'Install Details'
    },
    disabledNotice: 'Homebrew has disabled this package: {reason}',
    deprecatedNotice: 'Homebrew has deprecated this package: {reason}',
    noReason: 'no reason given',
    replacement: 'Use {token} instead',
    release: {
      new: 'New',
      title: 'What’s new in {version}',
      translated: 'Translated',
      source: {
        github_release: 'From GitHub Releases',
        sparkle: 'From the app’s update feed',
        webpage: 'From the release notes page',
        manual: 'Curated',
        editorial: 'OpenNavo editorial',
        homebrew: 'From Homebrew commits'
      },
      viewAll: 'See all {count} release | See all {count} releases',
      noNotes: 'This release has no separate notes.',
      emptyTitle: 'No release notes yet',
      prerelease: 'Pre-release',
      filterLabel: 'Filter versions',
      filterAll: 'All {count} | All {count}',
      filterWithNotes: 'With notes {count} | With notes {count}',
      filterMine: 'Installed by me {count} | Installed by me {count}',
      languageLabel: 'Text language',
      languageTranslated: 'Chinese',
      languageOriginal: 'Original',
      mineEmpty: 'None of the loaded versions were installed by you',
      count30d: 'Last 30 days',
      count30dUnit: 'release | releases',
      cadenceHint: {
        daily: 'Released almost daily',
        weekly: 'Released about weekly',
        biweekly: 'Released about every two weeks',
        monthly: 'Released about monthly',
        irregular: 'No regular schedule'
      },
      brewLabel: 'Added to Homebrew',
      brewSync: '≈ In sync',
      brewLater: '{time} later',
      brewEarlier: '{time} earlier',
      brewHint: '{earlier}/{compared} earlier',
      lagMinutes: '{n} min',
      lagHours: '{n} h',
      lagDays: '{n} day | {n} days',
      sourcesTitle: 'Sources',
      sourceInfo: {
        webpage: {
          title: 'Release notes page',
          body: "Highlights taken from the developer's release notes page"
        },
        github_release: {
          title: 'GitHub Releases',
          body: 'Release notes and dates published on GitHub'
        },
        sparkle: {
          title: 'In-app update feed',
          body: 'The Sparkle appcast the app checks for updates'
        },
        manual: {
          title: 'Curated',
          body: 'Written by our editors from official announcements'
        },
        editorial: {
          title: 'OpenNavo editorial',
          body: 'Release notes written by OpenNavo from official sources'
        },
        homebrew: {
          title: 'Homebrew commits',
          body: 'Version bumps in the Homebrew repository, giving the date it was added'
        },
        local: {
          title: 'This Mac',
          body: 'Every install and update you made in OpenNavo'
        }
      },
      localUpgrade: 'You updated from {from} to this version on {time} with OpenNavo · took {duration}',
      localInstall: 'You installed this version on {time} with OpenNavo · took {duration}',
      notify: 'Notify me about new versions',
      notifyHint: 'Shared by all apps · system notification and menu bar badge',
      pin: 'Pin the current version',
      pinHint: 'Same as brew pin; skipped by “Update all”',
      pinHintSelfUpdate: 'Same as brew pin, but {name} may still update itself'
    },
    monthly: {
      title: 'Monthly installs',
      d30: 'Last 30 days',
      avg90: '90-day avg',
      avg365: '1-year avg',
      full: '{count} install | {count} installs',
      trend: {
        rising: 'Installs are growing',
        slowing: 'Installs are slowing; most existing users update through the app itself',
        steady: 'Installs are steady'
      }
    },
    related: 'Similar Apps',
    screenshots: 'Screenshots',
    caveats: 'Caveats',
    info: {
      homepage: 'Homepage',
      binaries: 'Commands',
      autoUpdates: 'Updates',
      autoYes: 'Updates itself (auto_updates)',
      autoNo: 'Updated by Homebrew',
      uninstall: 'On uninstall',
      arch: 'Architecture',
      minMacos: 'Requires',
      license: 'License'
    },
    deps: {
      macos: 'Requires',
      formulae: 'Command-line dependencies',
      casks: 'App dependencies',
      emptyTitle: 'No dependencies',
      emptyDescription: 'Installing this doesn’t install anything else.',
      runtime: 'Runtime dependencies',
      build: 'Build dependencies',
      other: 'Other:',
      type: {
        runtime: 'runtime',
        build: 'build',
        test: 'test',
        optional: 'optional',
        recommended: 'recommended',
        usesFromMacos: 'uses macOS',
        cask: 'app'
      },
      conflicts: 'Conflicts',
      dependents: 'Used by {count} package | Used by {count} packages'
    },
    details: {
      tap: 'Tap',
      names: 'Also known as',
      location: 'Installs to',
      pkgs: 'Installer packages',
      kegOnly: 'keg-only',
      kegOnlyValue: 'Not linked into /opt/homebrew; add it to PATH yourself',
      download: 'Download URL',
      source: 'Homebrew definition',
      repo: 'Source code'
    },
    installed: 'Installed {version}',
    installedSelfUpdated: 'Installed {version} (updated by the app)',
    installedAt: 'Installed {date}',
    updateTo: 'Update to {version}',
    open: 'Open',
    getNeedsBrew: 'Install Homebrew First',
    actions: {
      label: 'More actions',
      uninstall: 'Uninstall',
      reinstall: 'Reinstall',
      pin: 'Pin Version',
      unpin: 'Unpin',
      reveal: 'Show in Finder',
      copyCommand: 'Copy brew Command',
      web: 'View on the Web'
    },
    uninstallConfirm: {
      title: 'Uninstall {name}?',
      description: 'This runs {command}.',
      zap: 'Also remove app data (--zap)',
      confirm: 'Uninstall'
    },
    commandCopied: 'brew command copied',
    offline: 'Connect to see screenshots and more',
    notFound: 'This package isn’t in the local catalog',
    pinned: 'Pinned',
    localSince: 'You updated to this version on {date}'
  },
  library: {
    title: 'Installed',
    summary: '{count} item · {size} | {count} items · {size}',
    summaryCount: '{count} item | {count} items',
    filterPlaceholder: 'Filter installed…',
    refresh: 'Refresh',
    empty: 'Nothing installed with Homebrew yet',
    emptyFiltered: 'Nothing matches the filters',
    columns: {
      name: 'Name',
      version: 'Version',
      size: 'Size',
      installedAt: 'Installed',
      status: 'Status',
      actions: 'Actions'
    },
    status: {
      installed: 'Installed',
      latest: 'Up to date',
      outdated: 'Update available',
      pinned: 'Pinned',
      selfUpdated: 'Up to date (updated by the app)',
      running: 'Updating {percent}',
      runningUnknown: 'Working',
      queued: 'Queued',
      unknown: 'Unknown'
    },
    dependency: 'Dependency of {names}',
    storage: {
      title: 'Storage',
      total: '{size} in total',
      caption: 'Disk usage',
      apps: 'Apps',
      cache: 'Download cache'
    },
    cleanup: {
      title: 'Clean Up Cache',
      description: 'Old versions and downloads, same as brew cleanup.',
      button: 'Free {size}',
      none: 'Nothing to clean up'
    },
    backup: {
      title: 'Backup & Migration',
      description: 'Export everything as a Brewfile and restore it on a new Mac in one step.',
      export: 'Export',
      restore: 'Restore',
      exported: '{count} package exported | {count} packages exported'
    },
    restore: {
      title: 'Restore from a Brewfile',
      summary: '{ready} to install · {installed} installed · {unsupported} not supported yet',
      install: 'Install {count} | Install {count}',
      status: {
        ready: 'Ready',
        installed: 'Installed',
        skipped: 'Nothing to do',
        unsupported: 'Not supported yet',
        invalid: 'Invalid',
        not_found: 'Not found'
      }
    },
    health: {
      title: 'Health Check',
      ok: 'brew doctor found no problems',
      warnings: '{count} warning | {count} warnings',
      run: 'Run Check',
      running: 'Checking…'
    }
  },
  updates: {
    title: 'Updates',
    summary:
      '{count} update available · about {size} to download | {count} updates available · about {size} to download',
    summaryNone: 'Everything is up to date',
    lastCheck: 'checked {time}',
    check: 'Check for Updates',
    checking: 'Checking…',
    updateAll: 'Update All',
    changelog: 'What’s New',
    update: 'Update',
    ignore: 'Ignore This Version',
    ignored: 'Ignoring {name} {version}',
    pinned: 'Pinned, won’t update',
    patch: 'Patch',
    empty: 'Everything is up to date',
    emptyHint: 'New versions will show up here',
    queued: '{count} added to the queue | {count} added to the queue',
    history: {
      title: 'History',
      subtitle: 'This Mac · {count} in the last 30 days | This Mac · {count} in the last 30 days',
      filterLabel: 'Result',
      all: 'All',
      succeeded: 'Succeeded',
      failed: 'Failed',
      today: 'Today · {date}',
      yesterday: 'Yesterday · {date}',
      viewLog: 'View Log',
      retry: 'Retry',
      canceled: 'Canceled',
      batch: '{action} {count} {kind} | {action} {count} {kind}',
      empty: 'No history yet'
    },
    month: {
      title: 'This Month',
      since: 'Since {date}',
      updated: 'Updated',
      updatedUnit: 'times',
      successRate: 'Success rate',
      successHint: '{count} failed | {count} failed'
    },
    auto: {
      title: 'Automatic Updates',
      subtitle: 'Run on schedule by the background helper',
      check: 'Check daily at {time}',
      checkHint: 'brew update + outdated',
      casks: 'Install app updates automatically',
      casksHint: 'When off, you only get a notification',
      greedy: 'Include self-updating apps',
      greedyHint: 'Same as --greedy'
    },
    mirror: {
      switch: 'Switch',
      latency: 'All traffic via mirror · {ms} ms'
    },
    next: {
      today: 'Today at {time}',
      tomorrow: 'Tomorrow at {time}',
      title: 'Next Check',
      text: '{time}. If the Mac is asleep, it runs after waking.',
      off: 'Automatic checks are off. Turn them on in Settings.'
    },
    log: {
      title: 'Log for {name}',
      empty: 'No log'
    }
  },
  history: {
    clear: 'Clear history',
    clearDescription: 'Clear all history? This cannot be undone. Installed apps and active tasks will not be affected.',
    cleared: 'History cleared',
    title: 'History',
    subtitle: 'Every install, update and uninstall on this Mac',
    search: 'Filter by name',
    exportCsv: 'Export CSV',
    exported: '{count} record exported | {count} records exported',
    empty: 'No records yet',
    duration: '{time}'
  },
  settings: {
    title: 'Settings',
    sections: {
      general: 'General',
      mirrors: 'Download Source',
      homebrew: 'Homebrew',
      privacy: 'Privacy',
      about: 'About'
    },
    general: {
      followSystem: 'Follow system (current: {language})',
      systemDialogsRestartHint: 'Restart OpenNavo to change the language of system dialogs.',
      language: 'Language',
      launchAtLogin: 'Launch at login',
      launchAtLoginHint: 'Starts with only the menu bar icon',
      keepInMenuBar: 'Keep in the menu bar after closing the window',
      trayShowCount: 'Show the number of updates in the menu bar',
      notifyUpdates: 'Notify me when updates are available',
      zapByDefault: 'Also remove app data when uninstalling',
      zapByDefaultHint: 'Same as brew uninstall --zap',
      updates: 'Update Checks',
      autoCheck: 'Check for updates daily',
      checkTime: 'Check time',
      runBrewUpdate: 'Update the Homebrew index before checking',
      runBrewUpdateHint: 'brew update'
    },
    mirrors: {
      title: 'Download Source',
      description: 'Applies to API metadata, bottles and brew’s own Git repositories.',
      copyEnv: 'Copy Terminal Variables',
      envCopied: 'Copied. Paste it into Terminal or your shell profile',
      envHint: 'Only affects brew run by OpenNavo. Copy these variables to use the same source in Terminal.'
    },
    homebrew: {
      path: 'brew path',
      auto: 'Detect automatically',
      version: 'Version',
      prefix: 'Prefix',
      analytics: 'Send anonymous analytics to Homebrew',
      analyticsFollow: 'Follow brew’s own setting',
      analyticsOff: 'Off (HOMEBREW_NO_ANALYTICS=1)',
      missing: 'Homebrew not found',
      install: 'Install Homebrew'
    },
    privacy: {
      crashReports: 'Send anonymous crash reports',
      crashReportsHint: 'Off by default. Only the stack trace is sent',
      appManagement: 'App Management',
      appManagementHint: 'Needed to update and uninstall apps',
      fullDiskAccess: 'Full Disk Access',
      fullDiskAccessHint: 'Needed to delete app data when uninstalling',
      enable: 'Turn On',
      waiting: 'Waiting…',
      granted: 'On',
      denied: 'Off',
      unknown: 'Can’t check',
      clearSearch: 'Clear Recent Searches'
    },
    about: {
      openSource: 'Open-source acknowledgements',
      view: 'View',
      draft: 'Pending review',
      version: 'Version {version}',
      website: 'Website',
      feedback: 'Send Feedback',
      privacy: 'Privacy',
      catalog: 'Local catalog: {count} package, synced {time} | Local catalog: {count} packages, synced {time}',
      sync: 'Sync Now'
    },
    saved: 'Saved'
  },
  mirrors: {
    official: 'Official',
    probe: 'Test Again',
    probing: 'Testing…',
    fastest: 'Fastest',
    recommended: 'Recommended',
    unavailable: 'Unavailable',
    configFailed: 'Can’t load the mirror list right now, so only the official source is available.',
    slowOfficial: 'The official source is slow ({official}). {name} responds in {latency}.',
    failedOfficial: 'Can’t reach the official source. {name} responds in {latency}.',
    useSuggested: 'Use {name}',
    selectedFailed: 'The selected source didn’t pass the speed test. Installing from it may fail.'
  },
  welcome: {
    title: 'Welcome to OpenNavo',
    subtitle: 'Let’s check this Mac first. It only takes a few seconds.',
    checks: 'System check',
    checking: 'Checking…',
    detectFailed: 'The check didn’t finish.',
    redetect: 'Check Again',
    macos: 'macOS {version} · {arch}',
    macosOk: 'Supported',
    clt: 'Xcode Command Line Tools',
    cltOk: 'Installed',
    cltMissing: 'Installed together with Homebrew',
    homebrew: 'Homebrew',
    homebrewOk: '{version} · {prefix}',
    homebrewMissing: 'Not found. {prefix} is empty',
    source: {
      title: 'Download Source',
      official: 'Official Source',
      mirror: 'Other Mirror',
      mirrorMissing: 'Mirror list unavailable',
      retry: 'Retry',
      hint: 'Later installs and updates also use this source. You can switch to another mirror in Settings → Download Source.',
      hintBrew: 'OpenNavo uses this source to install and update apps. Mirror variables set in Terminal are not read.'
    },
    install: 'Install Homebrew',
    passwordHint: 'The installer needs your administrator password in a system dialog. OpenNavo never stores it.',
    skip: 'Skip and Look Around',
    failed: {
      title: 'Homebrew wasn’t installed',
      E_SUDO: 'No administrator password was entered, so the installation was canceled.',
      E_DOWNLOAD: 'Couldn’t download the installer. Try another download source.',
      viewLog: 'View Log',
      logTitle: 'Homebrew installation log'
    },
    permissions: {
      title: 'Permissions',
      required: 'Required',
      optional: 'Optional',
      enable: 'Turn On',
      waiting: 'Waiting…',
      granted: 'On',
      confirm: 'I’ve Turned It On',
      startHint: 'Turn on App Management to get started.',
      appManagement: {
        title: 'Allow OpenNavo to manage apps',
        body: 'Needed to update and uninstall apps.',
        enable: 'Turn On App Management'
      },
      fullDiskAccess: {
        title: 'Full Disk Access',
        body: 'Needed to delete app data when uninstalling. You can turn it on later.',
        enable: 'Turn On Full Disk Access'
      }
    },
    done: 'Get Started',
    arch: {
      arm64: 'Apple silicon',
      x86_64: 'Intel'
    }
  },
  permission: {
    relaunch: {
      body: 'Turned on in System Settings. Reopen OpenNavo to apply it.',
      action: 'Reopen'
    },
    guide: {
      appManagement: 'App Management',
      fullDiskAccess: 'Full Disk Access',
      dragTitle: 'Drag OpenNavo into the list above',
      plusTitle: 'Click + below the list and choose OpenNavo',
      toggleHint: 'If OpenNavo is already in the list, just turn on its switch.',
      dragLabel: 'Drag the OpenNavo icon',
      close: 'Close',
      done: {
        appManagement: 'OpenNavo can now manage apps',
        fullDiskAccess: 'Full Disk Access is on'
      },
      doneHint: 'If macOS asks you to Quit & Reopen, click it.'
    },
    prompt: {
      appManagement: {
        title: 'Allow OpenNavo to manage apps',
        body: 'macOS blocked OpenNavo from changing the apps below. Turn on App Management, then try again.'
      },
      fullDiskAccess: {
        title: 'Full Disk Access needed',
        body: 'The apps below were removed, but their data wasn’t deleted. Deleting it needs Full Disk Access. Turn it on, then retry to finish uninstalling.'
      },
      enable: 'Turn On',
      waiting: 'Waiting…',
      retry: 'Retry',
      retryAll: 'Retry All',
      later: 'Later'
    },
    uninstall: {
      title: 'Deleting app data needs Full Disk Access',
      body: 'Turn it on before uninstalling, or uncheck the option to remove just the app.'
    }
  },
  deeplink: {
    installTitle: 'Install {name}?',
    installDescription:
      'A web page asked to install this on your Mac. Confirm to run the command below; cancel to do nothing.',
    installConfirm: 'Install',
    formulaUnsupported: 'OpenNavo only lists apps (Homebrew casks). This link points to a command-line tool.'
  },
  tray: {
    available: '{count} update available | {count} updates available',
    upToDate: 'Everything is up to date',
    upToDateHint: 'New versions show up here',
    running: {
      upgrade: 'Updating {name}',
      install: 'Installing {name}',
      uninstall: 'Uninstalling {name}',
      other: 'Working on {name}'
    },
    queued: '{count} more queued | {count} more queued',
    update: 'Update',
    updateAll: 'Update all ({count}) | Update all ({count})',
    more: '{count} more in OpenNavo | {count} more in OpenNavo',
    open: 'Open OpenNavo',
    settings: 'Settings',
    queuedToast: 'Added to the queue'
  },
  quit: {
    title: '{n} task is not finished | {n} tasks are not finished',
    description: 'Quitting stops the install in progress. Finished tasks are not affected.',
    confirm: 'Quit anyway',
    cancel: 'Keep running'
  },
  restore: {
    title: '{n} task did not finish last time | {n} tasks did not finish last time',
    description: 'Continue runs them in the original order; discard cancels them.',
    resume: 'Continue',
    discard: 'Discard'
  },
  updater: {
    autoCheck: 'Automatically check for OpenNavo updates',
    autoCheckHint: 'Check after launch, with one successful check per day.',
    foundTitle: 'New update available',
    foundDescription: 'OpenNavo {version} is ready to download',
    versionChange: 'Current version {current} → New version {next}',
    notesTitle: 'What’s new',
    noNotes: 'No release notes were provided.',
    fullNotes: 'View full release notes',
    later: 'Later',
    restartHint: 'Restart after installation. You can finish your current tasks first.',
    readyTitle: 'Update ready',
    downloadingUnknown: 'Downloading update…',
    installFailed: 'Download or installation failed. Please retry.',
    viewUpdate: 'View update',
    previewHint:
      'Development preview: simulated download and installation; no real update. Restart only closes the preview; you can view it again.',
    previewFailure: 'Simulate download failure',
    title: 'App updates',
    current: 'Current version {version}',
    check: 'Check for updates',
    latest: 'You have the latest version',
    available: 'Version {version} is available',
    install: 'Download and install',
    downloading: 'Downloading {percent}',
    installed: 'Installed; restart to finish',
    restart: 'Restart',
    busy: 'Tasks are running; restart after they finish',
    failed: 'Could not check for updates'
  },
  palette: {
    placeholder: 'Search apps or actions',
    apps: 'Apps',
    actions: 'Actions',
    navigation: 'Go To',
    open: 'Open',
    install: 'Install',
    update: 'Update {name}',
    reveal: 'Show {name} in Finder',
    viewAll: 'See all results for “{q}”',
    goTo: 'Go to {page}',
    installedVersion: 'Installed {version}',
    updatable: 'Update',
    copied: 'Copied {command}'
  },
  tasks: {
    ops: {
      install: 'Install',
      upgrade: 'Update',
      uninstall: 'Uninstall',
      reinstall: 'Reinstall',
      pin: 'Pin version',
      unpin: 'Unpin',
      cleanup: 'Clean up cache',
      update: 'Update Homebrew',
      install_homebrew: 'Install Homebrew'
    },
    running: {
      install: 'Installing {name}',
      upgrade: 'Updating {name}',
      uninstall: 'Uninstalling {name}',
      reinstall: 'Reinstalling {name}',
      pin: 'Pinning {name}',
      unpin: 'Unpinning {name}',
      cleanup: 'Cleaning up cache',
      update: 'Updating Homebrew',
      install_homebrew: 'Installing Homebrew'
    },
    phases: {
      preparing: 'Preparing',
      fetching: 'Fetching',
      downloading: 'Downloading',
      installing: 'Installing',
      linking: 'Linking',
      cleaning: 'Cleaning up',
      uninstalling: 'Uninstalling',
      updating: 'Updating index',
      finishing: 'Finishing'
    },
    step: 'Step {index} of {count}: {phase} | Step {index} of {count}: {phase}',
    remaining: 'About {time} left',
    queue: 'Queued',
    oneAtATime: 'brew runs one task at a time',
    triggers: {
      manual: 'Manual',
      schedule: 'Automatic',
      deeplink: 'From web',
      bundle: 'Batch',
      retry: 'Retry'
    },
    succeeded: '{action} {name} finished',
    failed: '{action} {name} failed'
  },
  errors: {
    E_APP_RUNNING: 'The app is running. Update deferred; quit the app and try again.',
    E_APP_QUIT_FAILED: 'The app did not quit. Update deferred; save your work, quit the app, and try again.',
    E_APP_CHECK_FAILED:
      'Could not check whether the app is running. Update deferred; refresh installed apps and try again.',

    actionFailed: 'That didn’t work',
    E_BREW_NOT_FOUND: 'Install Homebrew first',
    E_INVALID_ARG: 'Invalid argument',
    E_CHECKSUM: 'Download interrupted: SHA-256 checksum mismatch',
    E_DOWNLOAD: 'Download failed. Check your network or switch the download source',
    E_APP_EXISTS:
      'An app with the same name exists at the installation location. The operation did not complete; check the log. Retrying an installation checks again and asks for adoption confirmation',
    E_NOT_FOUND: 'Homebrew doesn’t have this package',
    E_DISABLED: 'Homebrew has disabled this package',
    E_LOCKED: 'Another Homebrew process is running. Retrying shortly',
    E_PERMISSION: 'No permission to change this app. Allow it in System Settings',
    E_FULL_DISK_ACCESS: 'Deleting app data needs Full Disk Access',
    E_SUDO: 'An administrator password is required',
    E_MACOS_VERSION: 'This Mac doesn’t meet the macOS requirement',
    E_REQUIRED_BY: 'Other packages depend on it, so it can’t be uninstalled',
    E_CONFLICT: 'Conflicts with an installed package',
    E_INTERRUPTED: 'The task was interrupted',
    E_TIMEOUT: 'No response for a long time',
    E_UNKNOWN: 'The operation failed. See the log for details',
    E_NETWORK: 'Can’t reach the OpenNavo service'
  },
  installConfirm: {
    title: 'Adopt the existing {name}?',
    description:
      'An app already exists at the installation location. Confirm to try managing it with Homebrew. Once adopted, you can update and uninstall it through OpenNavo.',
    matchHint:
      'Adoption requires the existing app to match the installation package. If it does not match, adoption will fail without forcing an overwrite.',
    confirm: 'Confirm adoption',
    blockedTitle: 'Cannot install {name} yet',
    blockedDescription:
      'The installation location or existing app could not be verified. No installation or adoption was performed. Check the app and installation details, then try again.'
  },
  runningApps: {
    title: 'Apps are running',
    description: 'Save your work before quitting the app to update it.',
    batchDescription: 'These apps are running. Save your work, then choose to skip them or quit them and update.',
    later: 'Later',
    skip: 'Skip these apps',
    quit: 'Quit and update',
    quitAll: 'Quit apps and update',
    reopen: 'Reopen after a successful update',
    quitHint: 'If an app stays open or you cancel quitting, its update will be deferred. Apps will not be force quit.',
    deferred: 'Deferred'
  },
  page: {
    comingSoon: 'This page will be filled in by a later task.'
  }
};

export default messages;
