pub mod brew;
pub mod brewfile;
pub mod catalog;
mod commands;
pub mod core;
pub mod db;
pub mod deeplink;
mod error;
pub mod events;
pub mod guide;
pub mod install_preflight;
pub mod installer;
pub mod library;
pub mod lifecycle;
pub mod locales_gen;
pub mod maintenance;
pub mod mirror;
pub mod model;
pub mod native_i18n;
pub mod native_menu;
pub mod notifications;
pub mod permissions;
pub mod queue;
pub mod running_apps;
pub mod scheduler;
pub mod settings;
pub mod system;
pub mod tray;
pub mod updates;

pub use error::AppError;

use tauri::Manager;
use tauri_specta::{Builder, collect_commands, collect_events};

const BINDINGS_HEADER: &str = "/* Generated by tauri-specta from Rust commands; do not edit. Regenerate with `pnpm --filter @opennavo/desktop gen`. */";

/// Collect all commands/events for both run() and binding export so generated TS matches actual registration.
pub fn specta_builder() -> Builder<tauri::Wry> {
    Builder::<tauri::Wry>::new()
        // Transmit time and bytes as numbers (06 §5.1); the pinned version's switch lives on Builder.
        .dangerously_cast_bigints_to_number()
        .commands(collect_commands![
            commands::app::app_info,
            commands::env::env_detect,
            commands::catalog::catalog_status,
            commands::catalog::catalog_sync,
            commands::catalog::catalog_search,
            commands::catalog::catalog_list,
            commands::catalog::catalog_get,
            commands::catalog::catalog_categories,
            commands::library::library_list,
            commands::library::library_refresh,
            commands::library::library_storage,
            commands::updates::updates_list,
            commands::updates::updates_status,
            commands::updates::updates_check,
            commands::updates::updates_ignore,
            commands::updates::updates_unignore,
            commands::settings::settings_get,
            commands::settings::locale_get,
            commands::settings::system_locale_get,
            commands::settings::settings_set,
            commands::mirror::mirror_probe,
            commands::tasks::apps_running,
            commands::tasks::install_preflight,
            commands::tasks::task_enqueue,
            commands::tasks::task_enqueue_many,
            commands::tasks::task_cancel,
            commands::tasks::task_list_active,
            commands::tasks::task_log,
            commands::tasks::history_list,
            commands::tasks::history_clear,
            commands::tasks::history_export_csv,
            commands::maintenance::brewfile_export,
            commands::maintenance::brewfile_preview,
            commands::maintenance::brewfile_install,
            commands::maintenance::cleanup_estimate,
            commands::maintenance::doctor_run,
            commands::system::app_open,
            commands::system::app_reveal,
            commands::system::system_open_privacy,
            commands::system::app_quit,
            commands::permissions::permissions_get,
            commands::permissions::permission_guide_open,
            commands::permissions::permission_guide_close,
            commands::permissions::permission_guide_info,
            commands::permissions::permission_guide_drag
        ])
        .events(collect_events![
            events::EnvChanged,
            events::CatalogSynced,
            events::TaskUpdated,
            events::TaskLog,
            events::LibraryEvent,
            events::UpdatesEvent,
            events::DeeplinkReceived,
            events::QuitEvent,
            events::LocaleEvent,
            events::UpdatesRequested,
            events::PermissionsChanged
        ])
}

pub async fn blocking<T: Send + 'static>(
    f: impl FnOnce() -> Result<T, AppError> + Send + 'static,
) -> Result<T, AppError> {
    tokio::task::spawn_blocking(f)
        .await
        .map_err(|e| AppError::new("E_UNKNOWN", "blocking_task").with_detail(e.to_string()))?
}

/// Export TS bindings to src/ipc/bindings.ts relative to src-tauri.
pub fn write_bindings(builder: &Builder<tauri::Wry>) -> Result<(), String> {
    builder
        .export(
            specta_typescript::Typescript::default().header(BINDINGS_HEADER),
            "../src/ipc/bindings.ts",
        )
        .map_err(|error| error.to_string())
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    let specta = specta_builder();
    let hidden = lifecycle::hidden_launch(&std::env::args().collect::<Vec<_>>());

    // Export bindings synchronously on development startup to match frontend types and commands; failure does not prevent running.
    #[cfg(debug_assertions)]
    if let Err(error) = write_bindings(&specta) {
        eprintln!("Failed to export IPC bindings: {error}");
    }

    let result = tauri::Builder::default()
        // Register single-instance first: a second instance forwards arguments including deep links to the running instance and exits (06 §4.3).
        .plugin(tauri_plugin_single_instance::init(|app, argv, _cwd| {
            if let Some(router) = app.try_state::<std::sync::Arc<deeplink::Router>>() {
                router.receive_args(&argv);
            } else {
                deeplink::show_main(app);
            }
        }))
        .plugin(tauri_plugin_deep_link::init())
        .plugin(tauri_plugin_updater::Builder::new().build())
        // Log Info and above by default; window/WebView debug logs are too noisy for log files.
        .plugin(
            tauri_plugin_log::Builder::new()
                .level(log::LevelFilter::Info)
                .level_for("tao", log::LevelFilter::Warn)
                .level_for("wry", log::LevelFilter::Warn)
                .build(),
        )
        .plugin(
            tauri_plugin_window_state::Builder::new()
                .with_state_flags(lifecycle::window_state_flags(hidden))
                .with_denylist(&[tray::LABEL])
                .build(),
        )
        .plugin(tauri_plugin_store::Builder::new().build())
        .plugin(tauri_plugin_notification::init())
        // Login startup uses --hidden, creating only the tray without showing the main window (06 §4.3).
        .plugin(tauri_plugin_autostart::init(
            tauri_plugin_autostart::MacosLauncher::LaunchAgent,
            Some(vec![lifecycle::LOGIN_ARG]),
        ))
        .plugin(tauri_plugin_positioner::init())
        .plugin(tauri_plugin_dialog::init())
        .plugin(tauri_plugin_opener::init())
        .plugin(tauri_plugin_clipboard_manager::init())
        .plugin(tauri_plugin_process::init())
        // Replace command handlers before window creation; preserve official plugin permissions/JS APIs and check tasks before restart.
        .plugin(lifecycle::guarded_process())
        .plugin(tauri_plugin_os::init())
        .invoke_handler(specta.invoke_handler())
        .on_window_event(|window, event| {
            if matches!(event, tauri::WindowEvent::Focused(true)) {
                commands::settings::refresh_system(window.app_handle());
            }
            if window.label() == "main"
                && let tauri::WindowEvent::CloseRequested { api, .. } = event
            {
                // Keep the window until confirmation finishes; hidden windows can still be restored by tray, notifications, or deep links.
                api.prevent_close();
                let action = window
                    .try_state::<std::sync::Arc<core::DesktopCore>>()
                    .and_then(|core| core.current_settings().ok())
                    .map(|settings| lifecycle::close_action(&settings))
                    .unwrap_or(lifecycle::CloseAction::Hide);
                match action {
                    lifecycle::CloseAction::Hide => {
                        let _ = window.hide();
                    }
                    lifecycle::CloseAction::RequestExit => window.app_handle().exit(0),
                }
            }
        })
        .on_page_load(|webview, payload| {
            if webview.label() != "main" {
                return;
            }
            if let Some(router) = webview.try_state::<std::sync::Arc<deeplink::Router>>() {
                match payload.event() {
                    tauri::webview::PageLoadEvent::Started => router.loading(),
                    tauri::webview::PageLoadEvent::Finished => {
                        let router = router.inner().clone();
                        tauri::async_runtime::spawn(async move {
                            tokio::time::sleep(std::time::Duration::from_millis(250)).await;
                            router.ready();
                        });
                    }
                }
            }
        })
        .setup(move |app| {
            specta.mount_events(app);
            let data = app.path().app_data_dir()?;
            let cache = app.path().app_cache_dir()?;
            let askpass = app.path().resolve(
                "resources/askpass/opennavo-askpass",
                tauri::path::BaseDirectory::Resource,
            )?;
            let sink = events::sink(app.handle().clone());
            deeplink::install(app.handle(), sink.clone());
            let core = tauri::async_runtime::block_on(blocking(move || {
                core::DesktopCore::open(data, cache, askpass, sink)
            }))?;
            let app_handle = app.handle().clone();
            let store_path = core.data_dir.join("settings.json");
            let save = tauri::async_runtime::block_on(blocking(move || {
                settings::plugin_save(&app_handle, &store_path)
            }))?;
            core.install_settings_save(save)?;
            app.manage(core.clone());
            app.manage(std::sync::Arc::new(guide::Guide::default()));
            lifecycle::install(app.handle(), hidden);
            let notifications = notifications::NativeNotifications::new(app.handle().clone());
            let weak = std::sync::Arc::downgrade(&notifications);
            let weak_core = std::sync::Arc::downgrade(&core);
            core.install_notice_sink(std::sync::Arc::new(move |notice| {
                if let (Some(native), Some(core)) = (weak.upgrade(), weak_core.upgrade())
                    && let Ok(settings) = core.current_settings()
                    && let Err(error) = native.send(notice, settings.locale)
                {
                    log::info!(
                        "System notifications temporarily unavailable: {}",
                        error.code
                    );
                }
            }))?;
            app.manage(notifications);
            settings::apply_apple_languages(&core.current_settings()?);
            settings::install_locale_observer(app.handle());
            native_menu::install(app.handle(), core.current_settings()?.locale)?;
            tray::install(app.handle())?;
            core.queue.start();
            core.start_catalog_sync();
            core.start_library_scan();
            scheduler::start(&core);
            Ok(())
        })
        .build(tauri::generate_context!());

    // Runtime initialization fails only during startup (configuration/system resources); continuing is impossible, so exit.
    match result {
        Ok(app) => app.run(lifecycle::run_event),
        Err(error) => {
            eprintln!("OpenNavo startup failed: {error}");
            std::process::exit(1);
        }
    }
}

/// The root-level name matches gen's --exact filter, avoiding successful commands that run zero tests.
#[cfg(test)]
#[test]
fn export_bindings() {
    write_bindings(&specta_builder()).expect("binding export must succeed");
}
