// Generated by tooling/scripts/gen-locales.mjs; edit locales.json instead.
#[derive(
    Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize, specta::Type,
)]
pub enum Locale {
    #[serde(rename = "en-US")]
    EnUs,
    #[serde(rename = "zh-CN")]
    ZhCn,
    #[serde(rename = "ja-JP")]
    JaJp,
    #[serde(rename = "es-ES")]
    EsEs,
    #[serde(rename = "pt-BR")]
    PtBr,
    #[serde(rename = "ru-RU")]
    RuRu,
}
pub type LocaleCode = Locale;
pub const LOCALES: [LocaleCode; 6] = [
    LocaleCode::EnUs,
    LocaleCode::ZhCn,
    LocaleCode::JaJp,
    LocaleCode::EsEs,
    LocaleCode::PtBr,
    LocaleCode::RuRu,
];
pub const DEFAULT_LOCALE: LocaleCode = LocaleCode::EnUs;
pub const AUTHORING_LOCALE: LocaleCode = LocaleCode::EnUs;
pub struct LocaleMetadata {
    pub code: LocaleCode,
    pub name: &'static str,
    pub prefix: &'static str,
    pub hreflang: &'static str,
    pub format_locale: &'static str,
    pub style: &'static str,
    pub plural_categories: &'static [&'static str],
}
pub const LOCALE_METADATA: [LocaleMetadata; 6] = [
    LocaleMetadata {
        code: LocaleCode::EnUs,
        name: "English",
        prefix: "",
        hreflang: "en",
        format_locale: "en-US",
        style: "Use clear, concise American English. Preserve product names and technical literals.",
        plural_categories: &["one", "other"],
    },
    LocaleMetadata {
        code: LocaleCode::ZhCn,
        name: "简体中文",
        prefix: "/zh",
        hreflang: "zh-Hans",
        format_locale: "zh-CN",
        style: "使用简洁自然的简体中文，保留品牌名与技术字面量。",
        plural_categories: &["other"],
    },
    LocaleMetadata {
        code: LocaleCode::JaJp,
        name: "日本語",
        prefix: "/ja",
        hreflang: "ja",
        format_locale: "ja-JP",
        style: "自然で簡潔なです・ます体を使い、製品名と技術的な文字列を保持してください。",
        plural_categories: &["other"],
    },
    LocaleMetadata {
        code: LocaleCode::EsEs,
        name: "Español",
        prefix: "/es",
        hreflang: "es",
        format_locale: "es-ES",
        style: "Usa español internacional neutro, claro y conciso. Conserva las marcas y los literales técnicos.",
        plural_categories: &["one", "other"],
    },
    LocaleMetadata {
        code: LocaleCode::PtBr,
        name: "Português (Brasil)",
        prefix: "/pt",
        hreflang: "pt-BR",
        format_locale: "pt-BR",
        style: "Use português brasileiro claro e conciso. Preserve marcas e literais técnicos.",
        plural_categories: &["one", "other"],
    },
    LocaleMetadata {
        code: LocaleCode::RuRu,
        name: "Русский",
        prefix: "/ru",
        hreflang: "ru",
        format_locale: "ru-RU",
        style: "Используйте ясный и краткий русский язык. Сохраняйте названия продуктов и технические литералы.",
        plural_categories: &["one", "few", "many", "other"],
    },
];
