package store

import (
	"context"
	"encoding/json"
	"time"

	"github.com/opennavo/opennavo/server/internal/domain"
)

const AdminCollectionJSON = `jsonb_build_object('id',c.id,'sourceLocale',c.source_locale,'slug',c.slug,'status',c.status,'sort',c.sort,'publishAt',c.publish_at,'unpublishAt',c.unpublish_at,'coverAssetId',c.cover_asset_id,'coverUrl',a.url,'createTime',c.created_at,'updateTime',c.updated_at,'createBy',creator.user_name,'updateBy',editor.user_name,'itemCount',(SELECT count(*) FROM collection_items WHERE collection_id=c.id),'i18n',COALESCE((SELECT jsonb_object_agg(i.locale,jsonb_build_object('status',i.status,'sourceLocale',i.source_locale,'sourceHash',i.source_hash,'model',i.model,'translatedAt',i.translated_at,'title',i.title,'subtitle',i.subtitle,'body',i.body)) FROM collection_i18n i WHERE i.collection_id=c.id),'{}'::jsonb),'items',COALESCE((SELECT jsonb_agg(jsonb_build_object('packageId',p.id,'kind',p.kind,'token',p.token,'name',p.name,'disabled',` + PackageDisabledSQL + `,'iconUrl',icon.url,'sort',ci.sort,'sourceLocale',ci.source_locale,'i18n',COALESCE((SELECT jsonb_object_agg(t.locale,jsonb_build_object('note',t.note,'status',t.status,'sourceLocale',t.source_locale,'sourceHash',t.source_hash,'model',t.model,'translatedAt',t.translated_at)) FROM collection_item_i18n t WHERE t.collection_id=ci.collection_id AND t.package_id=ci.package_id),'{}'::jsonb)) ORDER BY ci.sort,p.id) FROM collection_items ci JOIN packages p ON p.id=ci.package_id LEFT JOIN package_meta m ON m.package_id=p.id LEFT JOIN assets icon ON icon.id=m.icon_asset_id WHERE ci.collection_id=c.id),'[]'::jsonb))`
const AdminCollectionFrom = `FROM collections c LEFT JOIN assets a ON a.id=c.cover_asset_id LEFT JOIN admin_users creator ON creator.id=c.created_by LEFT JOIN admin_users editor ON editor.id=c.updated_by`
const AdminFeatureJSON = `jsonb_build_object('id',f.id,'sourceLocale',f.source_locale,'placement',f.placement,'categoryId',f.category_id,'targetType',f.target_type,'packageId',f.package_id,'packageName',p.name,'collectionId',f.collection_id,'collectionTitle',ci.title,'url',f.url,'glowColor',f.glow_color,'status',f.status,'startsAt',f.starts_at,'endsAt',f.ends_at,'sort',f.sort,'createTime',f.created_at,'updateTime',f.updated_at,'createBy',creator.user_name,'updateBy',editor.user_name,'i18n',COALESCE((SELECT jsonb_object_agg(i.locale,jsonb_build_object('status',i.status,'sourceLocale',i.source_locale,'sourceHash',i.source_hash,'model',i.model,'translatedAt',i.translated_at,'badge',i.badge,'title',i.title,'subtitle',i.subtitle,'body',i.body,'ctaLabel',i.cta_label)) FROM feature_i18n i WHERE i.feature_id=f.id),'{}'::jsonb))`
const AdminFeatureFrom = `FROM features f LEFT JOIN packages p ON p.id=f.package_id LEFT JOIN collections fc ON fc.id=f.collection_id LEFT JOIN LATERAL (SELECT t.* FROM collection_i18n t WHERE t.collection_id=fc.id AND t.locale IN (@onv_locale,fc.source_locale,'en-US') ORDER BY ` + adminLocaleOrder + ` LIMIT 1) ci ON TRUE LEFT JOIN admin_users creator ON creator.id=f.created_by LEFT JOIN admin_users editor ON editor.id=f.updated_by`

func (s *Store) AdminCollection(ctx context.Context, id int64) (json.RawMessage, error) {
	return s.JSONRow(ctx, "SELECT "+AdminCollectionJSON+" AS data "+AdminCollectionFrom+" WHERE c.id=?", id)
}
func (s *Store) AdminFeature(ctx context.Context, id int64) (json.RawMessage, error) {
	return s.JSONRow(ctx, "SELECT "+AdminFeatureJSON+" AS data "+AdminFeatureFrom+" WHERE f.id=?", id)
}

const VisibleCollection = `c.status IN ('scheduled','published') AND (c.publish_at IS NULL OR c.publish_at<=?) AND (c.unpublish_at IS NULL OR c.unpublish_at>?)`
const PublicCollectionJSON = `jsonb_build_object('slug',c.slug,'sourceLocale',c.source_locale,'machineTranslated',COALESCE(i.machine_translated,false),'title',i.title,'subtitle',i.subtitle,'body',i.body,'coverUrl',a.url,'updatedAt',c.updated_at,'itemCount',(SELECT count(*) FROM collection_items ci JOIN packages p ON p.id=ci.package_id LEFT JOIN package_meta m ON m.package_id=p.id WHERE ci.collection_id=c.id AND p.kind='cask' AND p.removed_at IS NULL AND NOT (p.disabled OR p.stale_disabled) AND NOT COALESCE(m.hidden,false)),'iconUrls',COALESCE((SELECT jsonb_agg(icon.url ORDER BY icons.sort,icons.package_id) FROM (SELECT ci.package_id,ci.sort,m.icon_asset_id FROM collection_items ci JOIN packages p ON p.id=ci.package_id LEFT JOIN package_meta m ON m.package_id=p.id WHERE ci.collection_id=c.id AND p.kind='cask' AND p.removed_at IS NULL AND NOT (p.disabled OR p.stale_disabled) AND NOT COALESCE(m.hidden,false) ORDER BY ci.sort,ci.package_id LIMIT 5) icons LEFT JOIN assets icon ON icon.id=icons.icon_asset_id),'[]'::jsonb),'previewItems',COALESCE((SELECT jsonb_agg(jsonb_build_object('kind',items.kind,'token',items.token,'displayName',COALESCE(NULLIF(pi.display_name,''),items.name,items.token),'sourceLocale',items.source_locale,'machineTranslated',COALESCE(pi.machine_translated,false),'iconUrl',icon.url,'accentColor',items.accent_color) ORDER BY items.sort,items.package_id) FROM (SELECT ci.package_id,ci.sort,p.kind,p.token,p.name,p.source_locale,m.icon_asset_id,m.accent_color FROM collection_items ci JOIN packages p ON p.id=ci.package_id LEFT JOIN package_meta m ON m.package_id=p.id WHERE ci.collection_id=c.id AND p.kind='cask' AND p.removed_at IS NULL AND NOT (p.disabled OR p.stale_disabled) AND NOT COALESCE(m.hidden,false) ORDER BY ci.sort,ci.package_id LIMIT 5) items LEFT JOIN assets icon ON icon.id=items.icon_asset_id LEFT JOIN LATERAL (SELECT t.* FROM package_i18n t CROSS JOIN (SELECT ?::text requested) lang WHERE COALESCE(NULLIF(t.display_name,''),NULLIF(t.summary,''),NULLIF(t.description,'')) IS NOT NULL AND t.package_id=items.package_id AND t.locale IN (lang.requested,items.source_locale,'en-US') ORDER BY ` + publicLocaleOrder + ` LIMIT 1) pi ON TRUE),'[]'::jsonb))`
const PublicCollectionFrom = `FROM collections c LEFT JOIN LATERAL (SELECT t.* FROM collection_i18n t CROSS JOIN (SELECT ?::text requested) lang WHERE NULLIF(t.title,'') IS NOT NULL AND t.collection_id=c.id AND t.locale IN (lang.requested,c.source_locale,'en-US') ORDER BY ` + publicLocaleOrder + ` LIMIT 1) i ON TRUE LEFT JOIN assets a ON a.id=c.cover_asset_id`

func (s *Store) PublicCollections(ctx context.Context, locale string, now time.Time, current, size int) ([]json.RawMessage, int64, error) {
	var total int64
	if err := s.DB.WithContext(ctx).Raw("SELECT count(*) FROM collections c WHERE "+VisibleCollection, now, now).Scan(&total).Error; err != nil {
		return nil, 0, err
	}
	offset, found := domain.PageOffset(current, size, total)
	if !found {
		return []json.RawMessage{}, total, nil
	}
	rows, err := s.JSONRows(ctx, "SELECT "+PublicCollectionJSON+" AS data "+PublicCollectionFrom+" WHERE "+VisibleCollection+" ORDER BY c.sort,c.id LIMIT ? OFFSET ?", locale, locale, now, now, size, offset)
	return rows, total, err
}
func (s *Store) PublicCollection(ctx context.Context, slug, locale string, now time.Time) (json.RawMessage, error) {
	return s.JSONRow(ctx, "SELECT "+PublicCollectionJSON+" AS data "+PublicCollectionFrom+" WHERE c.slug=? AND "+VisibleCollection, locale, locale, slug, now, now)
}
func (s *Store) CollectionItems(ctx context.Context, slug, locale string) ([]json.RawMessage, error) {
	return s.JSONRows(ctx, `SELECT jsonb_build_object('id',p.id,'kind',p.kind,'token',p.token,'note',i.note,'sourceLocale',ci.source_locale,'machineTranslated',COALESCE(i.machine_translated,false)) AS data FROM collection_items ci LEFT JOIN LATERAL (SELECT t.* FROM collection_item_i18n t CROSS JOIN (SELECT ?::text requested) lang WHERE t.note IS NOT NULL AND t.collection_id=ci.collection_id AND t.package_id=ci.package_id AND t.locale IN (lang.requested,ci.source_locale,'en-US') ORDER BY `+publicLocaleOrder+` LIMIT 1) i ON TRUE JOIN collections c ON c.id=ci.collection_id JOIN packages p ON p.id=ci.package_id LEFT JOIN package_meta m ON m.package_id=p.id WHERE c.slug=? AND p.kind='cask' AND p.removed_at IS NULL AND NOT (p.disabled OR p.stale_disabled) AND NOT COALESCE(m.hidden,false) ORDER BY ci.sort,p.id`, locale, slug)
}
func (s *Store) PublicFeatures(ctx context.Context, locale string, now time.Time) ([]json.RawMessage, error) {
	return s.JSONRows(ctx, `SELECT jsonb_build_object('id',f.id,'sourceLocale',f.source_locale,'placement',f.placement,'machineTranslated',COALESCE(i.machine_translated,false),'title',i.title,'badge',i.badge,'subtitle',i.subtitle,'body',i.body,'ctaLabel',i.cta_label,'glowColor',f.glow_color,'packageId',f.package_id,'target',jsonb_strip_nulls(jsonb_build_object('type',f.target_type,'kind',p.kind,'token',p.token,'slug',c.slug,'url',f.url))) AS data FROM features f LEFT JOIN LATERAL (SELECT t.* FROM feature_i18n t CROSS JOIN (SELECT ?::text requested) lang WHERE NULLIF(t.title,'') IS NOT NULL AND t.feature_id=f.id AND t.locale IN (lang.requested,f.source_locale,'en-US') ORDER BY `+publicLocaleOrder+` LIMIT 1) i ON TRUE LEFT JOIN packages p ON p.id=f.package_id LEFT JOIN package_meta m ON m.package_id=p.id LEFT JOIN collections c ON c.id=f.collection_id WHERE f.status IN('scheduled','published') AND (f.starts_at IS NULL OR f.starts_at<=?) AND (f.ends_at IS NULL OR f.ends_at>?) AND (f.target_type<>'package' OR (p.kind='cask' AND p.removed_at IS NULL AND NOT (p.disabled OR p.stale_disabled) AND NOT COALESCE(m.hidden,false))) AND (f.target_type<>'collection' OR (`+VisibleCollection+`)) ORDER BY f.sort,f.id`, locale, now, now, now, now)
}
