// Select names.ts icons from @iconify-json/lucide and generate src/icons/lucide.ts; commit output, CI verifies parity.
import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { getIcons } from '@iconify/utils';
import type { IconifyJSON } from '@iconify/types';
import { BUNDLED_ICONS } from '../src/icons/names.ts';

const require = createRequire(import.meta.url);
const source = JSON.parse(readFileSync(require.resolve('@iconify-json/lucide/icons.json'), 'utf8')) as IconifyJSON;
const subset = getIcons(source, [...BUNDLED_ICONS], true);
if (!subset) throw new Error('Cannot extract a subset from the Lucide icon set');

const missing = BUNDLED_ICONS.filter(name => !subset.icons[name] && !subset.aliases?.[name]);
if (missing.length) throw new Error(`Icons missing from Lucide: ${missing.join(', ')}`);

// Keep only rendering fields, avoiding meaningless changes from metadata such as lastModified.
const { prefix, icons, aliases, width, height } = subset;
const data = { prefix, icons, ...(aliases && Object.keys(aliases).length ? { aliases } : {}), width, height };

writeFileSync(
  new URL('../src/icons/lucide.ts', import.meta.url),
  `/* Generated by packages/ui/scripts/icons.ts; do not edit. After changing src/icons/names.ts, run \`pnpm --filter @opennavo/ui gen\`. */
import type { IconifyJSON } from '@iconify/types';

export const lucideSubset: IconifyJSON = ${JSON.stringify(data, null, 2)};
`
);
console.log(`src/icons/lucide.ts: ${Object.keys(icons).length} icons`);
