/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  catalog_category: () => import("@/views/catalog/category/index.vue"),
  "catalog_package-detail": () => import("@/views/catalog/package-detail/[id].vue"),
  catalog_package: () => import("@/views/catalog/package/index.vue"),
  changelog_release: () => import("@/views/changelog/release/index.vue"),
  changelog_review: () => import("@/views/changelog/review/index.vue"),
  content_announcement: () => import("@/views/content/announcement/index.vue"),
  "content_collection-detail": () => import("@/views/content/collection-detail/[id].vue"),
  content_collection: () => import("@/views/content/collection/index.vue"),
  content_feature: () => import("@/views/content/feature/index.vue"),
  content_glossary: () => import("@/views/content/glossary/index.vue"),
  dashboard: () => import("@/views/dashboard/index.vue"),
  "ops_agent-log": () => import("@/views/ops/agent-log/index.vue"),
  ops_feedback: () => import("@/views/ops/feedback/index.vue"),
  ops_job: () => import("@/views/ops/job/index.vue"),
  ops_search: () => import("@/views/ops/search/index.vue"),
  release_config: () => import("@/views/release/config/index.vue"),
  release_desktop: () => import("@/views/release/desktop/index.vue"),
  release_mirror: () => import("@/views/release/mirror/index.vue"),
  system_agent: () => import("@/views/system/agent/index.vue"),
  system_audit: () => import("@/views/system/audit/index.vue"),
  system_github: () => import("@/views/system/github/index.vue"),
  system_role: () => import("@/views/system/role/index.vue"),
  system_translation: () => import("@/views/system/translation/index.vue"),
  system_user: () => import("@/views/system/user/index.vue"),
  "user-center": () => import("@/views/user-center/index.vue"),
};
