/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'catalog',
    path: '/catalog',
    component: 'layout.base',
    meta: {
      title: 'catalog',
      i18nKey: 'route.catalog',
      icon: 'lucide:package',
      order: 2
    },
    children: [
      {
        name: 'catalog_category',
        path: '/catalog/category',
        component: 'view.catalog_category',
        meta: {
          title: 'catalog_category',
          i18nKey: 'route.catalog_category',
          order: 2,
          roles: ['R_ADMIN', 'R_EDITOR']
        }
      },
      {
        name: 'catalog_package',
        path: '/catalog/package',
        component: 'view.catalog_package',
        meta: {
          title: 'catalog_package',
          i18nKey: 'route.catalog_package',
          order: 1,
          roles: ['R_ADMIN', 'R_EDITOR', 'R_REVIEWER', 'R_OPS']
        }
      },
      {
        name: 'catalog_package-detail',
        path: '/catalog/package-detail/:id',
        component: 'view.catalog_package-detail',
        meta: {
          title: 'catalog_package-detail',
          i18nKey: 'route.catalog_package-detail',
          hideInMenu: true,
          activeMenu: 'catalog_package',
          roles: ['R_ADMIN', 'R_EDITOR', 'R_REVIEWER', 'R_OPS']
        }
      }
    ]
  },
  {
    name: 'changelog',
    path: '/changelog',
    component: 'layout.base',
    meta: {
      title: 'changelog',
      i18nKey: 'route.changelog',
      icon: 'lucide:rotate-ccw-clock',
      order: 4
    },
    children: [
      {
        name: 'changelog_release',
        path: '/changelog/release',
        component: 'view.changelog_release',
        meta: {
          title: 'changelog_release',
          i18nKey: 'route.changelog_release',
          order: 1,
          roles: ['R_ADMIN', 'R_EDITOR', 'R_REVIEWER', 'R_OPS']
        }
      },
      {
        name: 'changelog_review',
        path: '/changelog/review',
        component: 'view.changelog_review',
        meta: {
          title: 'changelog_review',
          i18nKey: 'route.changelog_review',
          order: 2,
          roles: ['R_ADMIN', 'R_EDITOR', 'R_REVIEWER']
        }
      }
    ]
  },
  {
    name: 'content',
    path: '/content',
    component: 'layout.base',
    meta: {
      title: 'content',
      i18nKey: 'route.content',
      icon: 'lucide:sparkles',
      order: 3
    },
    children: [
      {
        name: 'content_announcement',
        path: '/content/announcement',
        component: 'view.content_announcement',
        meta: {
          title: 'content_announcement',
          i18nKey: 'route.content_announcement',
          order: 4,
          roles: ['R_ADMIN']
        }
      },
      {
        name: 'content_collection',
        path: '/content/collection',
        component: 'view.content_collection',
        meta: {
          title: 'content_collection',
          i18nKey: 'route.content_collection',
          order: 1,
          roles: ['R_ADMIN', 'R_EDITOR']
        }
      },
      {
        name: 'content_collection-detail',
        path: '/content/collection-detail/:id',
        component: 'view.content_collection-detail',
        meta: {
          title: 'content_collection-detail',
          i18nKey: 'route.content_collection-detail',
          hideInMenu: true,
          activeMenu: 'content_collection',
          roles: ['R_ADMIN', 'R_EDITOR']
        }
      },
      {
        name: 'content_feature',
        path: '/content/feature',
        component: 'view.content_feature',
        meta: {
          title: 'content_feature',
          i18nKey: 'route.content_feature',
          order: 2,
          roles: ['R_ADMIN', 'R_EDITOR']
        }
      },
      {
        name: 'content_glossary',
        path: '/content/glossary',
        component: 'view.content_glossary',
        meta: {
          title: 'content_glossary',
          i18nKey: 'route.content_glossary',
          order: 3,
          roles: ['R_ADMIN']
        }
      }
    ]
  },
  {
    name: 'dashboard',
    path: '/dashboard',
    component: 'layout.base$view.dashboard',
    meta: {
      title: 'dashboard',
      i18nKey: 'route.dashboard',
      icon: 'lucide:layout-dashboard',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'ops',
    path: '/ops',
    component: 'layout.base',
    meta: {
      title: 'ops',
      i18nKey: 'route.ops',
      icon: 'lucide:activity',
      order: 5
    },
    children: [
      {
        name: 'ops_agent-log',
        path: '/ops/agent-log',
        component: 'view.ops_agent-log',
        meta: {
          title: 'ops_agent-log',
          i18nKey: 'route.ops_agent-log',
          order: 4,
          roles: ['R_ADMIN']
        }
      },
      {
        name: 'ops_feedback',
        path: '/ops/feedback',
        component: 'view.ops_feedback',
        meta: {
          title: 'ops_feedback',
          i18nKey: 'route.ops_feedback',
          order: 3,
          roles: ['R_ADMIN', 'R_EDITOR', 'R_OPS']
        }
      },
      {
        name: 'ops_job',
        path: '/ops/job',
        component: 'view.ops_job',
        meta: {
          title: 'ops_job',
          i18nKey: 'route.ops_job',
          order: 1,
          roles: ['R_ADMIN', 'R_OPS']
        }
      },
      {
        name: 'ops_search',
        path: '/ops/search',
        component: 'view.ops_search',
        meta: {
          title: 'ops_search',
          i18nKey: 'route.ops_search',
          order: 2,
          roles: ['R_ADMIN', 'R_EDITOR', 'R_OPS']
        }
      }
    ]
  },
  {
    name: 'release',
    path: '/release',
    component: 'layout.base',
    meta: {
      title: 'release',
      i18nKey: 'route.release',
      icon: 'lucide:rocket',
      order: 6
    },
    children: [
      {
        name: 'release_config',
        path: '/release/config',
        component: 'view.release_config',
        meta: {
          title: 'release_config',
          i18nKey: 'route.release_config',
          order: 3,
          roles: ['R_ADMIN', 'R_OPS']
        }
      },
      {
        name: 'release_desktop',
        path: '/release/desktop',
        component: 'view.release_desktop',
        meta: {
          title: 'release_desktop',
          i18nKey: 'route.release_desktop',
          order: 1,
          roles: ['R_ADMIN', 'R_OPS']
        }
      },
      {
        name: 'release_mirror',
        path: '/release/mirror',
        component: 'view.release_mirror',
        meta: {
          title: 'release_mirror',
          i18nKey: 'route.release_mirror',
          order: 2,
          roles: ['R_ADMIN', 'R_OPS']
        }
      }
    ]
  },
  {
    name: 'system',
    path: '/system',
    component: 'layout.base',
    meta: {
      title: 'system',
      i18nKey: 'route.system',
      icon: 'lucide:settings',
      order: 7
    },
    children: [
      {
        name: 'system_agent',
        path: '/system/agent',
        component: 'view.system_agent',
        meta: {
          title: 'system_agent',
          i18nKey: 'route.system_agent',
          order: 5,
          roles: ['R_SUPER']
        }
      },
      {
        name: 'system_audit',
        path: '/system/audit',
        component: 'view.system_audit',
        meta: {
          title: 'system_audit',
          i18nKey: 'route.system_audit',
          order: 3,
          roles: ['R_ADMIN']
        }
      },
      {
        name: 'system_github',
        path: '/system/github',
        component: 'view.system_github',
        meta: {
          title: 'system_github',
          i18nKey: 'route.system_github',
          order: 6,
          roles: ['R_ADMIN']
        }
      },
      {
        name: 'system_role',
        path: '/system/role',
        component: 'view.system_role',
        meta: {
          title: 'system_role',
          i18nKey: 'route.system_role',
          order: 2,
          roles: ['R_SUPER']
        }
      },
      {
        name: 'system_translation',
        path: '/system/translation',
        component: 'view.system_translation',
        meta: {
          title: 'system_translation',
          i18nKey: 'route.system_translation',
          order: 4,
          roles: ['R_ADMIN']
        }
      },
      {
        name: 'system_user',
        path: '/system/user',
        component: 'view.system_user',
        meta: {
          title: 'system_user',
          i18nKey: 'route.system_user',
          order: 1,
          roles: ['R_SUPER']
        }
      }
    ]
  },
  {
    name: 'user-center',
    path: '/user-center',
    component: 'layout.base$view.user-center',
    meta: {
      title: 'user-center',
      i18nKey: 'route.user-center',
      hideInMenu: true
    }
  }
];
