// Code generated by tooling/scripts/gen-locales.mjs; DO NOT EDIT.
package i18n

type LocaleCode string

const (
	enUS            LocaleCode = "en-US"
	zhCN            LocaleCode = "zh-CN"
	jaJP            LocaleCode = "ja-JP"
	esES            LocaleCode = "es-ES"
	ptBR            LocaleCode = "pt-BR"
	ruRU            LocaleCode = "ru-RU"
	DefaultLocale              = enUS
	AuthoringLocale            = enUS
)

var Locales = [...]LocaleCode{enUS, zhCN, jaJP, esES, ptBR, ruRU}

type LocaleMetadata struct {
	Name, Prefix, Hreflang, FormatLocale, Style string
	PluralCategories                            []string
}

var Metadata = map[LocaleCode]LocaleMetadata{
	enUS: {"English", "", "en", "en-US", "Use clear, concise American English. Preserve product names and technical literals.", []string{"one", "other"}},
	zhCN: {"简体中文", "/zh", "zh-Hans", "zh-CN", "使用简洁自然的简体中文，保留品牌名与技术字面量。", []string{"other"}},
	jaJP: {"日本語", "/ja", "ja", "ja-JP", "自然で簡潔なです・ます体を使い、製品名と技術的な文字列を保持してください。", []string{"other"}},
	esES: {"Español", "/es", "es", "es-ES", "Usa español internacional neutro, claro y conciso. Conserva las marcas y los literales técnicos.", []string{"one", "other"}},
	ptBR: {"Português (Brasil)", "/pt", "pt-BR", "pt-BR", "Use português brasileiro claro e conciso. Preserve marcas e literais técnicos.", []string{"one", "other"}},
	ruRU: {"Русский", "/ru", "ru", "ru-RU", "Используйте ясный и краткий русский язык. Сохраняйте названия продуктов и технические литералы.", []string{"one", "few", "many", "other"}},
}
