-- +goose Up
ALTER TABLE packages ADD COLUMN enrichment_source_hash TEXT;
ALTER TABLE releases ADD COLUMN summary_source_hash TEXT;
ALTER TABLE job_outbox ADD COLUMN available_at TIMESTAMPTZ NOT NULL DEFAULT now();
ALTER TABLE llm_usage DROP CONSTRAINT llm_usage_task_check;
ALTER TABLE llm_usage ADD CHECK(task IN ('enrich_package','translate_release','translate_content'));
CREATE TABLE i18n_settings (
 id BOOLEAN PRIMARY KEY DEFAULT true CHECK(id),
 enabled BOOLEAN NOT NULL DEFAULT true,
 enabled_locales JSONB NOT NULL DEFAULT '["en-US","zh-CN","ja-JP","es-ES","pt-BR","ru-RU"]',
 content_types JSONB NOT NULL DEFAULT '["package","release","category","collection","feature","screenshot","collection_item","desktop_release","mirror","announcement"]',
 upstream_fallback BOOLEAN NOT NULL DEFAULT true,
 model TEXT NOT NULL DEFAULT 'gpt-6-luna',
 reasoning_effort TEXT NOT NULL DEFAULT 'medium',
 monthly_token_budget BIGINT NOT NULL DEFAULT 30000000 CHECK(monthly_token_budget>0),
 updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
INSERT INTO i18n_settings(id) VALUES(true);
CREATE TABLE i18n_glossary (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 term TEXT NOT NULL UNIQUE CHECK(length(term)>0),
 translations JSONB NOT NULL DEFAULT '{}',
 do_not_translate BOOLEAN NOT NULL DEFAULT false,
 updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
INSERT INTO i18n_glossary(term,do_not_translate) VALUES('OpenNavo',true),('Homebrew',true),('macOS',true),('Markdown',true);
CREATE TABLE content_translation_sources (
 entity TEXT NOT NULL, object_key TEXT NOT NULL,
 ref JSONB NOT NULL, source_locale TEXT NOT NULL,
 source_hash TEXT NOT NULL, fields JSONB NOT NULL,
 updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
 PRIMARY KEY(entity,object_key)
);
CREATE TABLE translation_logs (
 id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
 entity TEXT NOT NULL, object_key TEXT NOT NULL, source_locale TEXT NOT NULL,
 target_locales JSONB NOT NULL, source_hash TEXT NOT NULL,
 model TEXT NOT NULL, status TEXT NOT NULL CHECK(status IN ('succeeded','failed','stale')),
 reason TEXT NOT NULL DEFAULT '', prompt_tokens BIGINT NOT NULL DEFAULT 0,
 completion_tokens BIGINT NOT NULL DEFAULT 0, reasoning_tokens BIGINT NOT NULL DEFAULT 0,
 cached_tokens BIGINT NOT NULL DEFAULT 0, latency_ms BIGINT NOT NULL DEFAULT 0,
 created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX translation_logs_object ON translation_logs(entity,object_key,id DESC);
CREATE TABLE translation_metrics (
 entity TEXT NOT NULL, status TEXT NOT NULL, requests BIGINT NOT NULL DEFAULT 0,
 tokens BIGINT NOT NULL DEFAULT 0, PRIMARY KEY(entity,status)
);
CREATE TABLE announcement_i18n (
 config_key TEXT NOT NULL REFERENCES app_config(key) ON DELETE CASCADE,
 locale TEXT NOT NULL CHECK(locale IN ('en-US','zh-CN','ja-JP','es-ES','pt-BR','ru-RU')),
 title TEXT, body TEXT, source_locale TEXT NOT NULL,
 status TEXT NOT NULL CHECK(status IN ('source','machine','manual','pending','failed')),
 source_hash TEXT, model TEXT, translated_at TIMESTAMPTZ,
 updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), machine_translated BOOLEAN NOT NULL DEFAULT false,
 fail_reason TEXT, PRIMARY KEY(config_key,locale)
);
CREATE TRIGGER announcement_provenance BEFORE INSERT OR UPDATE OF status ON announcement_i18n FOR EACH ROW EXECUTE FUNCTION preserve_translation_provenance();
ALTER TABLE package_i18n ADD COLUMN fail_reason TEXT;
ALTER TABLE category_i18n ADD COLUMN fail_reason TEXT;
ALTER TABLE collection_i18n ADD COLUMN fail_reason TEXT;
ALTER TABLE feature_i18n ADD COLUMN fail_reason TEXT;
ALTER TABLE screenshot_i18n ADD COLUMN fail_reason TEXT;
ALTER TABLE collection_item_i18n ADD COLUMN fail_reason TEXT;
ALTER TABLE desktop_release_i18n ADD COLUMN fail_reason TEXT;
ALTER TABLE mirror_i18n ADD COLUMN fail_reason TEXT;
-- +goose Down
-- +goose StatementBegin
DO $$ BEGIN RAISE EXCEPTION 'Content translation migration cannot be downgraded without losing history'; END $$;
-- +goose StatementEnd
