-- +goose Up
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- ========== Admin users and permissions ==========
CREATE TABLE admin_users (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_name       TEXT NOT NULL UNIQUE,
  password_hash   TEXT NOT NULL,                       -- argon2id-encoded string
  nick_name       TEXT NOT NULL DEFAULT '',
  email           TEXT,
  avatar_url      TEXT,
  status          TEXT NOT NULL DEFAULT '1' CHECK (status IN ('1','2')),  -- soybean convention: 1 enabled, 2 disabled
  session_version INTEGER NOT NULL DEFAULT 1,          -- Increment on password change/forced logout; old access tokens expire immediately
  failed_logins   INTEGER NOT NULL DEFAULT 0,
  locked_until    TIMESTAMPTZ,
  last_login_at   TIMESTAMPTZ,
  last_login_ip   TEXT,
  created_by      BIGINT,
  updated_by      BIGINT,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE admin_roles (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role_code  TEXT NOT NULL UNIQUE,                     -- R_SUPER / R_ADMIN / R_EDITOR / R_REVIEWER / R_OPS
  role_name  TEXT NOT NULL,
  role_desc  TEXT,
  status     TEXT NOT NULL DEFAULT '1' CHECK (status IN ('1','2')),
  builtin    BOOLEAN NOT NULL DEFAULT FALSE,           -- Built-in roles cannot be deleted
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE admin_user_roles (
  user_id BIGINT NOT NULL REFERENCES admin_users(id) ON DELETE CASCADE,
  role_id BIGINT NOT NULL REFERENCES admin_roles(id) ON DELETE CASCADE,
  PRIMARY KEY (user_id, role_id)
);

CREATE TABLE admin_permissions (
  code       TEXT PRIMARY KEY,                         -- For example catalog:package:edit
  name       TEXT NOT NULL,
  group_name TEXT NOT NULL
);

CREATE TABLE admin_role_permissions (
  role_id         BIGINT NOT NULL REFERENCES admin_roles(id) ON DELETE CASCADE,
  permission_code TEXT NOT NULL REFERENCES admin_permissions(code) ON DELETE CASCADE,
  PRIMARY KEY (role_id, permission_code)
);

CREATE TABLE admin_refresh_tokens (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     BIGINT NOT NULL REFERENCES admin_users(id) ON DELETE CASCADE,
  token_hash  TEXT NOT NULL UNIQUE,                    -- sha256(refresh token); never store plaintext
  family_id   UUID NOT NULL,                           -- Refresh chain derived from the same login
  expires_at  TIMESTAMPTZ NOT NULL,
  revoked_at  TIMESTAMPTZ,
  replaced_by BIGINT,
  user_agent  TEXT,
  ip          TEXT,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX admin_refresh_tokens_user ON admin_refresh_tokens (user_id);
CREATE INDEX admin_refresh_tokens_family ON admin_refresh_tokens (family_id);

CREATE TABLE audit_logs (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_id    BIGINT REFERENCES admin_users(id) ON DELETE SET NULL,
  action      TEXT NOT NULL,                           -- For example package.meta.update or collection.publish
  entity_type TEXT NOT NULL,
  entity_id   TEXT NOT NULL,
  before      JSONB,
  after       JSONB,
  ip          TEXT,
  user_agent  TEXT,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX audit_logs_entity ON audit_logs (entity_type, entity_id, created_at DESC);
CREATE INDEX audit_logs_actor ON audit_logs (actor_id, created_at DESC);

-- ========== Assets ==========
CREATE TABLE assets (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kind        TEXT NOT NULL CHECK (kind IN ('icon','screenshot','cover','og')),
  storage_key TEXT NOT NULL UNIQUE,
  url         TEXT NOT NULL,                           -- CDN URL
  mime        TEXT NOT NULL,
  width       INTEGER,
  height      INTEGER,
  bytes       BIGINT NOT NULL,
  sha256      TEXT NOT NULL,
  source_url  TEXT,
  created_by  BIGINT REFERENCES admin_users(id),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ========== Catalog ==========
CREATE TABLE packages (
  id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kind                    TEXT NOT NULL CHECK (kind IN ('cask','formula')),
  token                   TEXT NOT NULL,               -- visual-studio-code / ripgrep
  full_token              TEXT NOT NULL,
  tap                     TEXT NOT NULL,               -- homebrew/cask | homebrew/core
  name                    TEXT NOT NULL,               -- cask: name[0]；formula: name
  names                   TEXT[] NOT NULL DEFAULT '{}',-- All names, aliases and former names
  desc_en                 TEXT,
  homepage                TEXT,
  version                 TEXT NOT NULL,               -- Full version, possibly with a comma-separated build number
  version_base            TEXT NOT NULL,               -- Portion before the comma: 4.93.0,240920 -> 4.93.0
  license                 TEXT,
  auto_updates            BOOLEAN NOT NULL DEFAULT FALSE,
  deprecated              BOOLEAN NOT NULL DEFAULT FALSE,
  deprecation_date        DATE,
  deprecation_reason      TEXT,
  deprecation_replacement TEXT,                        -- 'cask:xxx' or 'formula:yyy'
  disabled                BOOLEAN NOT NULL DEFAULT FALSE,
  disable_date            DATE,
  disable_reason          TEXT,
  disable_replacement     TEXT,
  download_url            TEXT,
  download_size           BIGINT,                      -- HEAD Content-Length; nullable
  artifacts               JSONB NOT NULL DEFAULT '{}'::jsonb,  -- {"apps":[],"binaries":[],"pkgs":[],"uninstall":[]}
  dependencies            JSONB NOT NULL DEFAULT '{}'::jsonb,  -- See the platform support implementation
  conflicts_with          JSONB NOT NULL DEFAULT '{}'::jsonb,
  caveats                 TEXT,
  min_macos               TEXT,                        -- For example '13'
  supports_arm64          BOOLEAN NOT NULL DEFAULT TRUE,
  supports_x86_64         BOOLEAN NOT NULL DEFAULT TRUE,
  keg_only                BOOLEAN NOT NULL DEFAULT FALSE,
  ruby_source_path        TEXT,                        -- Casks/v/visual-studio-code.rb
  tap_git_head            TEXT,
  generated_date          DATE,
  is_font                 BOOLEAN NOT NULL DEFAULT FALSE,
  is_library              BOOLEAN NOT NULL DEFAULT FALSE,
  raw                     JSONB NOT NULL,              -- Raw Homebrew JSON
  raw_hash                TEXT NOT NULL,
  installs_30d            INTEGER NOT NULL DEFAULT 0,
  installs_90d            INTEGER NOT NULL DEFAULT 0,
  installs_365d           INTEGER NOT NULL DEFAULT 0,
  on_request_30d          INTEGER NOT NULL DEFAULT 0,  -- Formula only: installations on request
  on_request_90d          INTEGER NOT NULL DEFAULT 0,
  on_request_365d         INTEGER NOT NULL DEFAULT 0,
  rank_30d                INTEGER,                     -- Rank within the same kind (Casks exclude fonts)
  popularity              DOUBLE PRECISION NOT NULL DEFAULT 0,
  search_text             TEXT NOT NULL DEFAULT '',    -- Lowercase token, all names, Chinese name, pinyin and tags
  search_vector           TSVECTOR,
  first_seen_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
  version_changed_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  removed_at              TIMESTAMPTZ,                 -- No longer present in Homebrew
  created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (kind, token)
);
CREATE INDEX packages_search_text_trgm ON packages USING gin (search_text gin_trgm_ops);
CREATE INDEX packages_search_vector   ON packages USING gin (search_vector);
CREATE INDEX packages_names           ON packages USING gin (names);
CREATE INDEX packages_kind_popularity ON packages (kind, popularity DESC) WHERE removed_at IS NULL;
CREATE INDEX packages_kind_changed    ON packages (kind, version_changed_at DESC) WHERE removed_at IS NULL;

CREATE TABLE package_meta (
  package_id    BIGINT PRIMARY KEY REFERENCES packages(id) ON DELETE CASCADE,
  developer     TEXT,
  repo_url      TEXT,                                  -- Override the automatically detected GitHub repository
  hidden        BOOLEAN NOT NULL DEFAULT FALSE,        -- Exclude from browsing and search (still visible in installed lists)
  editor_choice BOOLEAN NOT NULL DEFAULT FALSE,
  tags          TEXT[] NOT NULL DEFAULT '{}',
  icon_asset_id BIGINT REFERENCES assets(id) ON DELETE SET NULL,
  icon_source   TEXT CHECK (icon_source IN ('manual','harvester','homepage')),
  accent_color  TEXT,                                  -- #RRGGBB
  notes         TEXT,                                  -- Internal notes
  updated_by    BIGINT REFERENCES admin_users(id),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE package_i18n (
  package_id   BIGINT NOT NULL REFERENCES packages(id) ON DELETE CASCADE,
  locale       TEXT NOT NULL CHECK (locale IN ('zh-CN','en-US')),
  display_name TEXT,                                   -- For example the Chinese name of WeChat; empty falls back to packages.name
  summary      TEXT,                                   -- One-sentence summary
  description  TEXT,                                   -- Detailed introduction in Markdown
  status       TEXT NOT NULL CHECK (status IN ('machine','needs_review','reviewed')),
  source       TEXT NOT NULL CHECK (source IN ('homebrew','rule','llm','human')),
  source_hash  TEXT,                                   -- sha256 of desc_en at generation time
  model        TEXT,
  reviewed_by  BIGINT REFERENCES admin_users(id),
  reviewed_at  TIMESTAMPTZ,
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (package_id, locale)
);
CREATE INDEX package_i18n_status ON package_i18n (locale, status);

CREATE TABLE categories (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_id         BIGINT REFERENCES categories(id) ON DELETE RESTRICT,
  slug              TEXT NOT NULL UNIQUE,
  icon              TEXT NOT NULL,                     -- Iconify name, for example lucide:code-xml
  applies_to        TEXT NOT NULL DEFAULT 'both' CHECK (applies_to IN ('cask','formula','both')),
  sort              INTEGER NOT NULL DEFAULT 0,
  visible           BOOLEAN NOT NULL DEFAULT TRUE,
  hidden_by_default BOOLEAN NOT NULL DEFAULT FALSE,    -- Fonts and libraries: hidden from lists by default
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE category_i18n (
  category_id BIGINT NOT NULL REFERENCES categories(id) ON DELETE CASCADE,
  locale      TEXT NOT NULL CHECK (locale IN ('zh-CN','en-US')),
  name        TEXT NOT NULL,
  description TEXT,
  PRIMARY KEY (category_id, locale)
);

CREATE TABLE package_categories (
  package_id  BIGINT NOT NULL REFERENCES packages(id) ON DELETE CASCADE,
  category_id BIGINT NOT NULL REFERENCES categories(id) ON DELETE CASCADE,
  is_primary  BOOLEAN NOT NULL DEFAULT FALSE,
  source      TEXT NOT NULL CHECK (source IN ('rule','llm','human')),
  confidence  REAL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (package_id, category_id)
);
CREATE UNIQUE INDEX package_categories_one_primary ON package_categories (package_id) WHERE is_primary;
CREATE INDEX package_categories_category ON package_categories (category_id);

CREATE TABLE package_screenshots (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  package_id BIGINT NOT NULL REFERENCES packages(id) ON DELETE CASCADE,
  asset_id   BIGINT NOT NULL REFERENCES assets(id) ON DELETE RESTRICT,
  sort       INTEGER NOT NULL DEFAULT 0,
  caption_zh TEXT,
  caption_en TEXT,
  theme      TEXT NOT NULL DEFAULT 'dark' CHECK (theme IN ('dark','light')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX package_screenshots_package ON package_screenshots (package_id, sort);

-- ========== Releases and changelogs ==========
CREATE TABLE package_versions (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  package_id        BIGINT NOT NULL REFERENCES packages(id) ON DELETE CASCADE,
  version           TEXT NOT NULL,
  version_base      TEXT NOT NULL,
  first_seen_at     TIMESTAMPTZ,                       -- First observed by our sync
  brew_committed_at TIMESTAMPTZ,                       -- Version-update commit timestamp in the Homebrew repository
  brew_commit_sha   TEXT,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (package_id, version)
);
CREATE INDEX package_versions_package ON package_versions (package_id, version_base);

CREATE TABLE releases (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  package_id    BIGINT NOT NULL REFERENCES packages(id) ON DELETE CASCADE,
  source        TEXT NOT NULL CHECK (source IN ('github_release','sparkle','webpage','manual')),
  source_key    TEXT NOT NULL,                         -- Tag name, appcast version or page URL
  version       TEXT NOT NULL,                         -- Normalized version
  title         TEXT,
  published_at  TIMESTAMPTZ,
  source_url    TEXT,
  body_markdown TEXT,                                  -- Source Markdown (at most 200 KB); NULL for patch versions without separate notes
  body_hash     TEXT,
  is_prerelease BOOLEAN NOT NULL DEFAULT FALSE,
  hidden        BOOLEAN NOT NULL DEFAULT FALSE,
  fetched_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (package_id, source, source_key)
);
CREATE INDEX releases_package_version   ON releases (package_id, version);
CREATE INDEX releases_package_published ON releases (package_id, published_at DESC);

CREATE TABLE release_i18n (
  release_id    BIGINT NOT NULL REFERENCES releases(id) ON DELETE CASCADE,
  locale        TEXT NOT NULL CHECK (locale IN ('zh-CN','en-US')),
  summary       TEXT,                                  -- At most 80 Chinese characters
  sections      JSONB NOT NULL DEFAULT '[]'::jsonb,    -- [{"area":"Agents","items":["..."]}]
  body_markdown TEXT,                                  -- Full-text translation
  status        TEXT NOT NULL CHECK (status IN ('pending','machine','needs_review','reviewed','failed','skipped')),
  fail_reason   TEXT,
  source_hash   TEXT,                                  -- Source body_hash at translation time
  model         TEXT,
  reviewed_by   BIGINT REFERENCES admin_users(id),
  reviewed_at   TIMESTAMPTZ,
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (release_id, locale)
);
CREATE INDEX release_i18n_todo ON release_i18n (status) WHERE status IN ('pending','needs_review','failed');

CREATE TABLE changelog_sources (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  package_id      BIGINT NOT NULL REFERENCES packages(id) ON DELETE CASCADE,
  type            TEXT NOT NULL CHECK (type IN ('github_releases','sparkle','webpage','homebrew_commits')),
  config          JSONB NOT NULL DEFAULT '{}'::jsonb,  -- See job definitions
  priority        INTEGER NOT NULL DEFAULT 100,        -- Lower numbers take precedence
  enabled         BOOLEAN NOT NULL DEFAULT TRUE,
  resolved_by     TEXT NOT NULL CHECK (resolved_by IN ('auto','manual')),
  etag            TEXT,
  last_modified   TEXT,
  last_fetched_at TIMESTAMPTZ,
  last_status     TEXT NOT NULL DEFAULT 'never'
                  CHECK (last_status IN ('never','ok','not_modified','error','rate_limited','not_found')),
  last_error      TEXT,
  fail_count      INTEGER NOT NULL DEFAULT 0,
  next_fetch_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (package_id, type)
);
CREATE INDEX changelog_sources_due ON changelog_sources (next_fetch_at) WHERE enabled;

-- ========== Analytics ==========
CREATE TABLE analytics_snapshots (
  package_id     BIGINT NOT NULL REFERENCES packages(id) ON DELETE CASCADE,
  snapshot_date  DATE NOT NULL,
  installs_30d   INTEGER NOT NULL,
  installs_90d   INTEGER NOT NULL,
  installs_365d  INTEGER NOT NULL,
  on_request_30d INTEGER NOT NULL DEFAULT 0,
  rank_30d       INTEGER,
  PRIMARY KEY (package_id, snapshot_date)
);

-- ========== Client catalog distribution ==========
CREATE TABLE catalog_changes (
  seq        BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,   -- Exposed publicly as cursor
  package_id BIGINT NOT NULL,
  kind       TEXT NOT NULL,
  token      TEXT NOT NULL,
  op         TEXT NOT NULL CHECK (op IN ('upsert','delete')),
  reason     TEXT NOT NULL CHECK (reason IN ('homebrew','content','asset')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX catalog_changes_created ON catalog_changes (created_at);

CREATE TABLE catalog_snapshots (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  format_version INTEGER NOT NULL,
  seq            BIGINT NOT NULL,                      -- catalog_changes.seq covered by the snapshot
  item_count     INTEGER NOT NULL,
  storage_key    TEXT NOT NULL,
  url            TEXT NOT NULL,
  sha256         TEXT NOT NULL,
  bytes          BIGINT NOT NULL,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ========== Content operations ==========
CREATE TABLE collections (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug           TEXT NOT NULL UNIQUE,
  status         TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','scheduled','published','archived')),
  publish_at     TIMESTAMPTZ,
  unpublish_at   TIMESTAMPTZ,
  sort           INTEGER NOT NULL DEFAULT 0,
  cover_asset_id BIGINT REFERENCES assets(id) ON DELETE SET NULL,
  created_by     BIGINT REFERENCES admin_users(id),
  updated_by     BIGINT REFERENCES admin_users(id),
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE collection_i18n (
  collection_id BIGINT NOT NULL REFERENCES collections(id) ON DELETE CASCADE,
  locale        TEXT NOT NULL CHECK (locale IN ('zh-CN','en-US')),
  title         TEXT NOT NULL,
  subtitle      TEXT,
  body          TEXT,                                  -- Markdown
  PRIMARY KEY (collection_id, locale)
);

CREATE TABLE collection_items (
  collection_id BIGINT NOT NULL REFERENCES collections(id) ON DELETE CASCADE,
  package_id    BIGINT NOT NULL REFERENCES packages(id) ON DELETE CASCADE,
  sort          INTEGER NOT NULL DEFAULT 0,
  note_zh       TEXT,
  note_en       TEXT,
  PRIMARY KEY (collection_id, package_id)
);

CREATE TABLE features (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  placement     TEXT NOT NULL CHECK (placement IN ('home_hero','home_secondary','category_top')),
  category_id   BIGINT REFERENCES categories(id) ON DELETE CASCADE,
  target_type   TEXT NOT NULL CHECK (target_type IN ('package','collection','url')),
  package_id    BIGINT REFERENCES packages(id) ON DELETE CASCADE,
  collection_id BIGINT REFERENCES collections(id) ON DELETE CASCADE,
  url           TEXT,
  glow_color    TEXT,                                  -- Hero glow color; empty uses brand purple #5B5BD6
  status        TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','scheduled','published','archived')),
  starts_at     TIMESTAMPTZ,
  ends_at       TIMESTAMPTZ,
  sort          INTEGER NOT NULL DEFAULT 0,
  created_by    BIGINT REFERENCES admin_users(id),
  updated_by    BIGINT REFERENCES admin_users(id),
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  CHECK (placement <> 'category_top' OR category_id IS NOT NULL),
  CHECK ((target_type = 'package'    AND package_id IS NOT NULL)
      OR (target_type = 'collection' AND collection_id IS NOT NULL)
      OR (target_type = 'url'        AND url IS NOT NULL))
);

CREATE TABLE feature_i18n (
  feature_id BIGINT NOT NULL REFERENCES features(id) ON DELETE CASCADE,
  locale     TEXT NOT NULL CHECK (locale IN ('zh-CN','en-US')),
  badge      TEXT,                                     -- "Featured this week"
  title      TEXT NOT NULL,                            -- 「Ghostty 1.3」
  subtitle   TEXT,                                     -- Second-line accent text, for example "A terminal that feels this fast."
  body       TEXT,                                     -- Only **bold** markup is allowed for highlighting
  cta_label  TEXT,
  PRIMARY KEY (feature_id, locale)
);

-- ========== Search ==========
CREATE TABLE search_synonyms (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  terms      TEXT[] NOT NULL,                          -- Mutual synonyms: {vscode, visual studio code}
  enabled    BOOLEAN NOT NULL DEFAULT TRUE,
  created_by BIGINT REFERENCES admin_users(id),
  updated_by BIGINT REFERENCES admin_users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE search_queries (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  query              TEXT NOT NULL,
  normalized         TEXT NOT NULL,
  locale             TEXT NOT NULL,
  platform           TEXT NOT NULL CHECK (platform IN ('web','desktop')),
  result_count       INTEGER NOT NULL,
  clicked_package_id BIGINT,
  clicked_position   INTEGER,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX search_queries_created    ON search_queries (created_at);
CREATE INDEX search_queries_normalized ON search_queries (normalized, created_at);

-- ========== Feedback ==========
CREATE TABLE feedback (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type         TEXT NOT NULL CHECK (type IN ('wrong_info','install_failed','broken_link','suggest_package','translation','other')),
  package_id   BIGINT REFERENCES packages(id) ON DELETE SET NULL,
  content      TEXT NOT NULL,
  contact      TEXT,
  platform     TEXT NOT NULL CHECK (platform IN ('web','desktop')),
  app_version  TEXT,
  os_version   TEXT,
  error_code   TEXT,
  status       TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open','in_progress','resolved','rejected')),
  handler_note TEXT,
  handled_by   BIGINT REFERENCES admin_users(id),
  handled_at   TIMESTAMPTZ,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX feedback_status ON feedback (status, created_at DESC);

-- ========== Client releases and configuration ==========
CREATE TABLE desktop_releases (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version      TEXT NOT NULL,
  channel      TEXT NOT NULL DEFAULT 'stable' CHECK (channel IN ('stable','beta')),
  status       TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','published','rolled_back')),
  min_macos    TEXT NOT NULL DEFAULT '13.0',
  notes_zh     TEXT NOT NULL DEFAULT '',
  notes_en     TEXT NOT NULL DEFAULT '',
  artifacts    JSONB NOT NULL,                         -- See desktop release handling
  pub_date     TIMESTAMPTZ,
  published_by BIGINT REFERENCES admin_users(id),
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (version, channel)
);

CREATE TABLE mirrors (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key             TEXT NOT NULL UNIQUE,                -- official / tuna / ustc / aliyun
  name_zh         TEXT NOT NULL,
  name_en         TEXT NOT NULL,
  api_domain      TEXT,                                -- NULL means unset (official)
  bottle_domain   TEXT,
  brew_git_remote TEXT,
  core_git_remote TEXT,
  probe_url       TEXT NOT NULL,                       -- Client speed-test URL (HEAD)
  recommended     BOOLEAN NOT NULL DEFAULT FALSE,
  enabled         BOOLEAN NOT NULL DEFAULT TRUE,
  sort            INTEGER NOT NULL DEFAULT 0,
  updated_by      BIGINT REFERENCES admin_users(id),
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE app_config (
  key         TEXT PRIMARY KEY,                        -- For example desktop.minSupportedVersion
  value       JSONB NOT NULL,
  description TEXT,
  updated_by  BIGINT REFERENCES admin_users(id),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ========== Jobs and LLM ==========
CREATE TABLE sync_runs (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_type     TEXT NOT NULL,
  trigger      TEXT NOT NULL CHECK (trigger IN ('schedule','manual','event')),
  triggered_by BIGINT REFERENCES admin_users(id),
  status       TEXT NOT NULL CHECK (status IN ('running','succeeded','failed','partial')),
  stats        JSONB NOT NULL DEFAULT '{}'::jsonb,
  error        TEXT,
  started_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  finished_at  TIMESTAMPTZ
);
CREATE INDEX sync_runs_type_started ON sync_runs (job_type, started_at DESC);

CREATE TABLE llm_usage (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task              TEXT NOT NULL CHECK (task IN ('enrich_package','translate_release')),
  ref_id            BIGINT NOT NULL,
  model             TEXT NOT NULL,
  reasoning_effort  TEXT NOT NULL,
  prompt_tokens     INTEGER NOT NULL DEFAULT 0,
  completion_tokens INTEGER NOT NULL DEFAULT 0,                -- Includes reasoning tokens
  reasoning_tokens  INTEGER NOT NULL DEFAULT 0,                -- completion_tokens_details.reasoning_tokens
  cached_tokens     INTEGER NOT NULL DEFAULT 0,                -- prompt_tokens_details.cached_tokens
  latency_ms        INTEGER NOT NULL DEFAULT 0,
  finish_reason     TEXT,
  cost_usd          NUMERIC(12,6),                             -- Calculated only when unit pricing is configured; otherwise NULL
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX llm_usage_created ON llm_usage (created_at);

-- +goose Down
DROP TABLE IF EXISTS llm_usage, sync_runs, app_config, mirrors, desktop_releases,
  feedback, search_queries, search_synonyms, feature_i18n, features, collection_items,
  collection_i18n, collections, catalog_snapshots, catalog_changes, analytics_snapshots,
  changelog_sources, release_i18n, releases, package_versions, package_screenshots,
  package_categories, category_i18n, categories, package_i18n, package_meta, packages,
  assets, audit_logs, admin_refresh_tokens, admin_role_permissions, admin_permissions,
  admin_user_roles, admin_roles, admin_users CASCADE;
