import { lucideSubset } from './lucide';

export interface IconData {
  /** Inner SVG content from bundled Lucide data generated by scripts/icons.ts. */
  body: string;
  width: number;
  height: number;
}

/** Get a bundled icon, optionally prefixed lucide:; return undefined if not bundled. */
export function getIcon(name: string): IconData | undefined {
  const [prefix, id] = name.includes(':') ? name.split(':', 2) : [lucideSubset.prefix, name];
  if (prefix !== lucideSubset.prefix || !id) return undefined;
  const key = lucideSubset.aliases?.[id]?.parent ?? id;
  const icon = lucideSubset.icons[key];
  if (!icon) return undefined;
  return {
    body: icon.body,
    width: icon.width ?? lucideSubset.width ?? 24,
    height: icon.height ?? lucideSubset.height ?? 24
  };
}

export { BUNDLED_ICONS, CATEGORY_ICONS, UI_ICONS } from './names';
