// Bundled Lucide icons: offline and direct SSR SVG. Add icons here, then run pnpm --filter @opennavo/ui gen.
// Unlisted icons do not render or contact Iconify; warn in development console.

/** UI icons (08 §6). */
export const UI_ICONS = [
  'compass',
  'layout-grid',
  'chart-no-axes-column',
  'package',
  'circle-arrow-down',
  'rotate-ccw-clock',
  'sliders-horizontal',
  'search',
  'download',
  'arrow-up-right',
  'arrow-right',
  'arrow-left',
  'arrow-up',
  'arrow-down',
  'copy',
  'ellipsis',
  'pin',
  'refresh-cw',
  'check',
  'x',
  'triangle-alert',
  'circle-alert',
  'info',
  'trash',
  'cloud',
  'folder',
  'square-terminal',
  'shield-check',
  'chevron-right',
  'chevron-left',
  'chevron-down',
  'chevron-up',
  'plus',
  'minus',
  'menu',
  'settings',
  'list-filter',
  'wifi-off',
  'inbox',
  'clock',
  'calendar',
  'tag',
  'hard-drive',
  'file-text',
  'command',
  'square'
] as const;

/** Category icons (03 §5.3 seed categories). */
export const CATEGORY_ICONS = [
  'sparkles',
  'code-xml',
  'square-terminal',
  'braces',
  'database',
  'boxes',
  'zap',
  'notebook-pen',
  'briefcase',
  'globe',
  'message-circle',
  'pen-tool',
  'clapperboard',
  'wrench',
  'panel-top',
  'network',
  'shield',
  'cpu',
  'gamepad-2',
  'graduation-cap',
  'type',
  'library'
] as const;

export const BUNDLED_ICONS: readonly string[] = [...new Set([...UI_ICONS, ...CATEGORY_ICONS])];
