/* Generated by tauri-specta from Rust commands; do not edit. Regenerate with `pnpm --filter @opennavo/desktop gen`. */
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	appInfo: () => typedError<AppInfo, AppError>(__TAURI_INVOKE("app_info")),
	envDetect: () => typedError<EnvInfo, AppError>(__TAURI_INVOKE("env_detect")),
	catalogStatus: () => typedError<CatalogStatus, AppError>(__TAURI_INVOKE("catalog_status")),
	catalogSync: (force: boolean) => typedError<SyncResult, AppError>(__TAURI_INVOKE("catalog_sync", { force })),
	catalogSearch: (query: SearchQuery) => typedError<Page<SearchHit_Serialize>, AppError>(__TAURI_INVOKE("catalog_search", { query })),
	catalogList: (query: ListQuery) => typedError<Page<CatalogItem_Serialize>, AppError>(__TAURI_INVOKE("catalog_list", { query })),
	catalogGet: (kind: Kind, token: string) => typedError<{
	sourceLocale: Locale,
	kind: Kind,
	token: string,
	name: string,
	names: string[],
	displayName: LocalizedText,
	summary: LocalizedText,
	version: string,
	homepage: string | null,
	autoUpdates: boolean,
	deprecated: boolean,
	disabled: boolean,
	hidden: boolean,
	isFont: boolean,
	isLibrary: boolean,
	categories: string[],
	tags: string[],
	installs30d: number,
	rank30d: number | null,
	popularity: number | null,
	iconUrl: string | null,
	accentColor: string | null,
	apps: string[],
	binaries: string[],
	pinyin: string | null,
	versionChangedAt: string,
	installs90d?: number | null,
	installs365d?: number | null,
	downloadSize: number | null,
	onRequest: OnRequest | null,
} | null, AppError>(__TAURI_INVOKE("catalog_get", { kind, token })),
	catalogCategories: () => typedError<CategoryItem[], AppError>(__TAURI_INVOKE("catalog_categories")),
	libraryList: () => typedError<InstalledItem[], AppError>(__TAURI_INVOKE("library_list")),
	libraryRefresh: () => typedError<InstalledItem[], AppError>(__TAURI_INVOKE("library_refresh")),
	libraryStorage: () => typedError<StorageSummary, AppError>(__TAURI_INVOKE("library_storage")),
	updatesList: () => typedError<OutdatedItem[], AppError>(__TAURI_INVOKE("updates_list")),
	updatesStatus: () => typedError<UpdatesStatus, AppError>(__TAURI_INVOKE("updates_status")),
	updatesCheck: (runBrewUpdate: boolean) => typedError<OutdatedItem[], AppError>(__TAURI_INVOKE("updates_check", { runBrewUpdate })),
	updatesIgnore: (target: TaskTarget, version: string | null, until: number | null) => typedError<null, AppError>(__TAURI_INVOKE("updates_ignore", { target, version, until })),
	updatesUnignore: (target: TaskTarget) => typedError<null, AppError>(__TAURI_INVOKE("updates_unignore", { target })),
	settingsGet: () => typedError<Settings, AppError>(__TAURI_INVOKE("settings_get")),
	localeGet: () => typedError<Locale, AppError>(__TAURI_INVOKE("locale_get")),
	settingsSet: (settings: Settings) => typedError<Settings, AppError>(__TAURI_INVOKE("settings_set", { settings })),
	mirrorProbe: (mirrors: MirrorInput[]) => typedError<MirrorProbe[], AppError>(__TAURI_INVOKE("mirror_probe", { mirrors })),
	appsRunning: (targets: TaskTarget[]) => typedError<RunningApp[], AppError>(__TAURI_INVOKE("apps_running", { targets })),
	installPreflight: (target: TaskTarget) => typedError<InstallPreflight, AppError>(__TAURI_INVOKE("install_preflight", { target })),
	taskEnqueue: (op: TaskOp, target: {
	kind: Kind,
	token: string,
} | null, options: TaskOptions, trigger: TaskTrigger) => typedError<Task, AppError>(__TAURI_INVOKE("task_enqueue", { op, target, options, trigger })),
	taskEnqueueMany: (op: TaskOp, targets: TaskTarget[], options: TaskOptions, trigger: TaskTrigger) => typedError<Task[], AppError>(__TAURI_INVOKE("task_enqueue_many", { op, targets, options, trigger })),
	taskCancel: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("task_cancel", { id })),
	taskListActive: () => typedError<Task[], AppError>(__TAURI_INVOKE("task_list_active")),
	taskLog: (id: string, tail: number | null) => typedError<string, AppError>(__TAURI_INVOKE("task_log", { id, tail })),
	historyList: (query: HistoryQuery) => typedError<Page<Task>, AppError>(__TAURI_INVOKE("history_list", { query })),
	historyClear: () => typedError<number, AppError>(__TAURI_INVOKE("history_clear")),
	historyExportCsv: (path: string) => typedError<number, AppError>(__TAURI_INVOKE("history_export_csv", { path })),
	brewfileExport: (path: string, targets: TaskTarget[] | null) => typedError<number, AppError>(__TAURI_INVOKE("brewfile_export", { path, targets })),
	brewfilePreview: (path: string) => typedError<BrewfilePreview, AppError>(__TAURI_INVOKE("brewfile_preview", { path })),
	brewfileInstall: (targets: TaskTarget[]) => typedError<Task[], AppError>(__TAURI_INVOKE("brewfile_install", { targets })),
	cleanupEstimate: () => typedError<CleanupEstimate, AppError>(__TAURI_INVOKE("cleanup_estimate")),
	doctorRun: () => typedError<DoctorReport, AppError>(__TAURI_INVOKE("doctor_run")),
	appOpen: (target: TaskTarget) => typedError<null, AppError>(__TAURI_INVOKE("app_open", { target })),
	appReveal: (target: TaskTarget) => typedError<null, AppError>(__TAURI_INVOKE("app_reveal", { target })),
	systemOpenPrivacy: (pane: PrivacyPane) => typedError<null, AppError>(__TAURI_INVOKE("system_open_privacy", { pane })),
	appQuit: () => typedError<null, AppError>(__TAURI_INVOKE("app_quit")),
	/**  Current privacy permissions (06 §12.3, §12.6): read-only, without prompts. */
	permissionsGet: () => typedError<Permissions, AppError>(__TAURI_INVOKE("permissions_get")),
	/**  Open the corresponding System Settings panel and adjacent guidance overlay (06 §12.7). */
	permissionGuideOpen: (pane: PrivacyPane) => typedError<null, AppError>(__TAURI_INVOKE("permission_guide_open", { pane })),
	permissionGuideClose: () => typedError<null, AppError>(__TAURI_INVOKE("permission_guide_close")),
	permissionGuideInfo: () => typedError<PermissionGuideInfo, AppError>(__TAURI_INVOKE("permission_guide_info")),
	/**  Drag OpenNavo's icon from the overlay. This synchronous command runs on the main thread while the current event is still mouse-down. */
	permissionGuideDrag: () => typedError<null, AppError>(__TAURI_INVOKE("permission_guide_drag")),
};

/** Events */
export const events = {
	appQuitRequested: makeEvent<QuitEvent>("app:quit-requested"),
	catalogSynced: makeEvent<CatalogSynced>("catalog:synced"),
	deeplinkReceived: makeEvent<DeeplinkReceived>("deeplink:received"),
	envChanged: makeEvent<EnvChanged>("env:changed"),
	libraryChanged: makeEvent<LibraryEvent>("library:changed"),
	localeChanged: makeEvent<LocaleEvent>("locale:changed"),
	permissionsChanged: makeEvent<PermissionsChanged>("permissions:changed"),
	taskLog: makeEvent<TaskLog>("task:log"),
	taskUpdated: makeEvent<TaskUpdated>("task:updated"),
	updatesChanged: makeEvent<UpdatesEvent>("updates:changed"),
	updatesRequested: makeEvent<UpdatesRequested>("updates:requested"),
};

/* Types */
/**  Error type for all commands (06 §5.1): `code` is a 06 §5.4 client error code used to select UI copy. */
export type AppError = {
	code: string,
	message: string,
	detail: string | null,
};

/**  Client information for About, X-Client-Version headers, and diagnostics. */
export type AppInfo = {
	version: string,
	/**  Platform, e.g. macos. */
	os: string,
	/**  CPU architecture, e.g. aarch64 or x86_64. */
	arch: string,
};

export type BrewInfo = {
	path: string,
	prefix: string,
	version: string,
};

export type BrewfileEntry = {
	line: number,
	raw: string,
	kind: Kind | null,
	token: string | null,
	status: BrewfileEntryStatus,
	reason: string | null,
};

export type BrewfileEntryStatus = "ready" | "installed" | "skipped" | "unsupported" | "invalid" | "not_found";

export type BrewfilePreview = {
	entries: BrewfileEntry[],
	ready: number,
	installed: number,
	unsupported: number,
};

/**  Date strings retain the HTTP catalog format; local IPC times use Unix milliseconds. */
export type CatalogItem = CatalogItem_Serialize | CatalogItem_Deserialize;

/**  Date strings retain the HTTP catalog format; local IPC times use Unix milliseconds. */
export type CatalogItem_Deserialize = {
	sourceLocale?: Locale,
	kind: Kind,
	token: string,
	name: string,
	names: string[],
	displayName?: LocalizedText,
	summary?: LocalizedText,
	version: string,
	homepage: string | null,
	autoUpdates: boolean,
	deprecated: boolean,
	disabled: boolean,
	hidden: boolean,
	isFont: boolean,
	isLibrary: boolean,
	categories: string[],
	tags: string[],
	installs30d: number,
	rank30d: number | null,
	popularity: number | null,
	iconUrl: string | null,
	accentColor: string | null,
	apps: string[],
	binaries: string[],
	pinyin: string | null,
	versionChangedAt: string,
	installs90d?: number | null,
	installs365d?: number | null,
	downloadSize: number | null,
	onRequest: OnRequest | null,
};

/**  Date strings retain the HTTP catalog format; local IPC times use Unix milliseconds. */
export type CatalogItem_Serialize = {
	sourceLocale: Locale,
	kind: Kind,
	token: string,
	name: string,
	names: string[],
	displayName: LocalizedText,
	summary: LocalizedText,
	version: string,
	homepage: string | null,
	autoUpdates: boolean,
	deprecated: boolean,
	disabled: boolean,
	hidden: boolean,
	isFont: boolean,
	isLibrary: boolean,
	categories: string[],
	tags: string[],
	installs30d: number,
	rank30d: number | null,
	popularity: number | null,
	iconUrl: string | null,
	accentColor: string | null,
	apps: string[],
	binaries: string[],
	pinyin: string | null,
	versionChangedAt: string,
	installs90d?: number | null,
	installs365d?: number | null,
	downloadSize: number | null,
	onRequest: OnRequest | null,
};

export type CatalogStatus = {
	cursor: number,
	itemCount: number,
	syncedAt: number | null,
	syncing: boolean,
};

export type CatalogSynced = CatalogStatus;

export type CategoryAppliesTo = "cask" | "formula" | "both";

export type CategoryItem = {
	slug: string,
	parent: string | null,
	name: string,
	icon: string,
	appliesTo: CategoryAppliesTo,
	hiddenByDefault: boolean,
	sort: number,
	packageCount: number,
};

export type CleanupEstimate = {
	bytes: number,
	fileCount: number,
	items: CleanupItem[],
};

export type CleanupItem = {
	path: string,
	bytes: number | null,
};

export type DeepLinkAction = "install";

export type DeepLinkEvent = {
	url: string,
	route: string,
	action: DeepLinkAction | null,
};

export type DeeplinkReceived = DeepLinkEvent;

export type DoctorReport = {
	ok: boolean,
	warnings: DoctorWarning[],
	ranAt: number,
};

export type DoctorWarning = {
	title: string,
	body: string,
};

export type EnvChanged = EnvInfo;

export type EnvInfo = {
	macosVersion: string,
	arch: string,
	rosetta: boolean,
	cltInstalled: boolean,
	brew: BrewInfo | null,
	appManagement: PermissionState,
};

export type HistoryQuery = {
	q: string | null,
	ops: TaskOp[],
	states: TaskState[],
	target: TaskTarget | null,
	includeScheduledUpdates: boolean,
	from: number | null,
	to: number | null,
	limit: number,
	offset: number,
};

export type InstallPreflight = {
	name: string,
	paths: string[],
	status: InstallPreflightStatus,
};

export type InstallPreflightStatus = "ready" | "managed" | "conflict" | "blocked";

export type InstalledItem = {
	kind: Kind,
	token: string,
	name: string,
	installedVersion: string,
	actualVersion: string | null,
	latestVersion: string | null,
	status: InstalledStatus,
	onRequest: boolean,
	requiredBy: string[],
	installedAt: number | null,
	sizeBytes: number | null,
	appPaths: string[],
	iconPath: string | null,
	autoUpdates: boolean,
	pinned: boolean,
};

export type InstalledStatus = "up_to_date" | "outdated" | "pinned" | "self_updated" | "unknown";

export type Kind = "cask" | "formula";

export type LibraryChangeReason = "task" | "refresh" | "startup";

export type LibraryChanged = {
	reason: LibraryChangeReason,
};

export type LibraryEvent = LibraryChanged;

export type ListQuery = {
	kind: Kind | null,
	category: string | null,
	sort: ListSort,
	includeFonts: boolean,
	includeLibraries: boolean,
	includeDisabled: boolean,
	limit: number,
	offset: number,
};

export type ListSort = "popular" | "updated" | "name" | "installs30d" | "installs90d" | "installs365d";

export type Locale = "en-US" | "zh-CN" | "ja-JP" | "es-ES" | "pt-BR" | "ru-RU";

export type LocaleChanged = {
	locale: Locale,
};

export type LocaleEvent = LocaleChanged;

export type LocaleMode = "system" | "manual";

/**  Sparse maps accept legacy nulls; IPC emits only text actually present. */
export type LocalizedText = Partial<{ [key in Locale]: string }>;

export type MirrorChoice = {
	key: string,
	apiDomain: string | null,
	bottleDomain: string | null,
	brewGitRemote: string | null,
	coreGitRemote: string | null,
};

export type MirrorInput = {
	key: string,
	name: string,
	probeUrl: string,
	apiDomain: string | null,
	bottleDomain: string | null,
	brewGitRemote: string | null,
	coreGitRemote: string | null,
};

export type MirrorProbe = {
	key: string,
	ok: boolean,
	latencyMs: number | null,
	status: number | null,
	error: string | null,
};

export type OnRequest = {
	d30: number,
	d90: number,
	d365: number,
};

export type OutdatedItem = {
	kind: Kind,
	token: string,
	name: string,
	installedVersion: string,
	currentVersion: string,
	autoUpdates: boolean,
	pinned: boolean,
	ignored: boolean,
	dependents: number,
	downloadSize: number | null,
};

export type Page<T> = {
	total: number,
	items: T[],
};

/**  Permission overlay capability (§12.7): development builds are not .app bundles and cannot drag an icon. */
export type PermissionGuideInfo = {
	draggable: boolean,
};

export type PermissionState = "granted" | "denied" | "unknown";

/**  Privacy state (§12.3, §12.6): payload for permissions_get and permissions:changed. */
export type Permissions = {
	/**  App Management: prefer system preflight; effective Full Disk Access implies granted; otherwise infer from task outcomes if preflight is unavailable. */
	appManagement: PermissionState,
	/**  Full Disk Access: effective only if this process can read protected directories. */
	fullDiskAccess: PermissionState,
	/**  Enabled in System Settings but not yet effective; quit and reopen OpenNavo. */
	relaunchRequired: boolean,
};

/**  Permission changes detected by guidance polling (06 §12.7), broadcast to all windows. */
export type PermissionsChanged = Permissions;

export type PrivacyPane = "app_management" | "notifications" | "full_disk_access";

export type QuitEvent = QuitRequested;

export type QuitRequested = {
	running: number,
	queued: number,
};

export type RunningApp = {
	target: TaskTarget,
	name: string,
};

export type SearchHit = SearchHit_Serialize | SearchHit_Deserialize;

export type SearchHit_Deserialize = {
	item: CatalogItem_Deserialize,
	score: number | null,
	matchedName: string | null,
};

export type SearchHit_Serialize = {
	item: CatalogItem_Serialize,
	score: number | null,
	matchedName: string | null,
};

export type SearchQuery = {
	q: string,
	kind: Kind | null,
	category: string | null,
	includeDisabled: boolean,
	limit: number,
	offset: number,
};

export type Settings = {
	onboardingCompleted: boolean,
	localeMode: LocaleMode,
	locale: Locale,
	launchAtLogin: boolean,
	keepInMenuBarOnClose: boolean,
	trayShowCount: boolean,
	autoCheck: boolean,
	checkTime: string,
	runBrewUpdateOnCheck: boolean,
	includeGreedy: boolean,
	autoUpgradeFormulae: boolean,
	autoUpgradeCasks: boolean,
	notifyUpdates: boolean,
	mirror: MirrorChoice,
	brewPath: string | null,
	homebrewAnalytics: boolean | null,
	crashReports: boolean,
	zapByDefault: boolean,
};

export type StorageSummary = {
	appsBytes: number,
	appCount: number,
	formulaeBytes: number,
	formulaCount: number,
	cacheBytes: number,
	complete: boolean,
	measuredAt: number,
};

export type SyncMode = "snapshot" | "delta" | "none";

export type SyncResult = {
	mode: SyncMode,
	applied: number,
	cursor: number,
};

export type Task = {
	id: string,
	op: TaskOp,
	target: TaskTarget | null,
	options: TaskOptions,
	trigger: TaskTrigger,
	state: TaskState,
	phase: TaskPhase | null,
	percent: number | null,
	bytesDone: number | null,
	bytesTotal: number | null,
	speedBps: number | null,
	stepIndex: number | null,
	stepCount: number | null,
	fromVersion: string | null,
	toVersion: string | null,
	error: AppError | null,
	exitCode: number | null,
	logPath: string | null,
	createdAt: number,
	startedAt: number | null,
	finishedAt: number | null,
};

export type TaskLog = TaskLogEvent;

export type TaskLogEvent = {
	id: string,
	lines: string[],
};

export type TaskOp = "install" | "upgrade" | "uninstall" | "reinstall" | "pin" | "unpin" | "cleanup" | "update" | "install_homebrew";

export type TaskOptions = {
	zap?: boolean,
	adopt?: boolean,
	greedy?: boolean,
	/**  Cask uninstall retry only (§6.3): after partial zap failure the app is moved but Caskroom retains a backup; finish with --force. */
	force?: boolean,
	quitRunning?: boolean,
	reopen?: boolean,
};

export type TaskPhase = "preparing" | "fetching" | "downloading" | "installing" | "linking" | "cleaning" | "uninstalling" | "updating" | "finishing";

export type TaskState = "queued" | "running" | "succeeded" | "failed" | "canceled";

export type TaskTarget = {
	kind: Kind,
	token: string,
};

export type TaskTrigger = "manual" | "schedule" | "deeplink" | "bundle" | "retry";

export type TaskUpdated = Task;

export type UpdatesChanged = {
	count: number,
};

export type UpdatesEvent = UpdatesChanged;

/**  The main window centrally confirms tray updates; never close other apps from the small popover. */
export type UpdatesRequested = TaskTarget[];

export type UpdatesStatus = {
	checkedAt: number | null,
	nextCheckAt: number | null,
	checking: boolean,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

