// Read only the locale manifest; do not modify existing platform Locale types or translation files.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { spawnSync } from 'node:child_process';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '../..');
const manifest = JSON.parse(readFileSync(resolve(root, 'packages/shared/src/locales.json'), 'utf8'));
const codes = manifest.locales.map(locale => locale.code);
if (
  new Set(codes).size !== codes.length ||
  !codes.includes(manifest.defaultLocale) ||
  !codes.includes(manifest.authoringLocale)
) {
  throw new Error('Duplicate locale codes or missing default/authoring locale in the manifest');
}
for (const locale of manifest.locales) {
  const categories = locale.pluralCategories;
  if (
    !Array.isArray(categories) ||
    !categories.includes('other') ||
    new Set(categories).size !== categories.length ||
    categories.some(category => !['zero', 'one', 'two', 'few', 'many', 'other'].includes(category))
  ) {
    throw new Error(`Invalid plural categories: ${locale.code}`);
  }
}
const quote = JSON.stringify;
const goName = code => code.replace('-', '');
const rustName = code =>
  code
    .split('-')
    .map(part => part[0].toUpperCase() + part.slice(1).toLowerCase())
    .join('');
const formatted = (command, args, source) => {
  const result = spawnSync(command, args, { input: source, encoding: 'utf8', cwd: command === 'rustfmt' ? resolve(root, 'apps/desktop/src-tauri') : root });
  if (result.status !== 0) throw new Error(`${command}: ${result.stderr}`);
  return result.stdout;
};
const ts = formatted(
  'pnpm',
  ['exec', 'oxfmt', '--config', 'tooling/config/.oxfmtrc.json', '--stdin-filepath', 'packages/shared/src/locales.gen.ts'],
  `// Generated by tooling/scripts/gen-locales.mjs; edit locales.json instead.\nexport const LOCALES = ${quote(codes)} as const;\nexport type LocaleCode = (typeof LOCALES)[number];\nexport const DEFAULT_LOCALE: LocaleCode = ${quote(manifest.defaultLocale)};\nexport const AUTHORING_LOCALE: LocaleCode = ${quote(manifest.authoringLocale)};\nexport const LOCALE_METADATA = ${JSON.stringify(Object.fromEntries(manifest.locales.map(locale => [locale.code, locale])), null, 2)} as const;\n`
);
const go = formatted(
  'gofmt',
  [],
  `// Code generated by tooling/scripts/gen-locales.mjs; DO NOT EDIT.\npackage i18n\ntype LocaleCode string\nconst (\n${codes.map(code => `${goName(code)} LocaleCode = ${quote(code)}`).join('\n')}\nDefaultLocale = ${goName(manifest.defaultLocale)}\nAuthoringLocale = ${goName(manifest.authoringLocale)}\n)\nvar Locales = [...]LocaleCode{${codes.map(goName).join(',')}}\ntype LocaleMetadata struct { Name, Prefix, Hreflang, FormatLocale, Style string; PluralCategories []string }\nvar Metadata = map[LocaleCode]LocaleMetadata{\n${manifest.locales.map(locale => `${goName(locale.code)}: {${['name', 'prefix', 'hreflang', 'formatLocale', 'style'].map(key => quote(locale[key])).join(',')}, []string{${locale.pluralCategories.map(quote).join(',')}}},`).join('\n')}\n}\n`
);
const rust = formatted(
  'rustfmt',
  ['--emit', 'stdout', '--edition', '2024'],
  `// Generated by tooling/scripts/gen-locales.mjs; edit locales.json instead.\n#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize, specta::Type)]\npub enum Locale {\n${codes.map(code => `#[serde(rename = ${quote(code)})]\n${rustName(code)},`).join('\n')}\n}\npub type LocaleCode = Locale;\npub const LOCALES: [LocaleCode; ${codes.length}] = [${codes.map(code => `LocaleCode::${rustName(code)}`).join(',')}];\npub const DEFAULT_LOCALE: LocaleCode = LocaleCode::${rustName(manifest.defaultLocale)};\npub const AUTHORING_LOCALE: LocaleCode = LocaleCode::${rustName(manifest.authoringLocale)};\npub struct LocaleMetadata { pub code: LocaleCode, pub name: &'static str, pub prefix: &'static str, pub hreflang: &'static str, pub format_locale: &'static str, pub style: &'static str, pub plural_categories: &'static [&'static str] }\npub const LOCALE_METADATA: [LocaleMetadata; ${codes.length}] = [${manifest.locales.map(locale => `LocaleMetadata {code: LocaleCode::${rustName(locale.code)}, name: ${quote(locale.name)}, prefix: ${quote(locale.prefix)}, hreflang: ${quote(locale.hreflang)}, format_locale: ${quote(locale.formatLocale)}, style: ${quote(locale.style)}, plural_categories: &[${locale.pluralCategories.map(quote).join(',')}] }`).join(',')}];\n`
);
for (const [path, content] of Object.entries({
  'packages/shared/src/locales.gen.ts': ts,
  'apps/server/internal/i18n/locales.gen.go': go,
  'apps/desktop/src-tauri/src/locales_gen.rs': rust
})) {
  const target = resolve(root, path);
  if (process.argv.includes('--check')) {
    if (readFileSync(target, 'utf8') !== content) throw new Error(`Generated locale file is outdated: ${path}`);
  } else {
    mkdirSync(dirname(target), { recursive: true });
    writeFileSync(target, content);
  }
}
