// Generated by tooling/scripts/gen-locales.mjs; edit locales.json instead.
export const LOCALES = ['en-US', 'zh-CN', 'ja-JP', 'es-ES', 'pt-BR', 'ru-RU'] as const;
export type LocaleCode = (typeof LOCALES)[number];
export const DEFAULT_LOCALE: LocaleCode = 'en-US';
export const AUTHORING_LOCALE: LocaleCode = 'en-US';
export const LOCALE_METADATA = {
  'en-US': {
    code: 'en-US',
    name: 'English',
    prefix: '',
    hreflang: 'en',
    formatLocale: 'en-US',
    style: 'Use clear, concise American English. Preserve product names and technical literals.',
    pluralCategories: ['one', 'other']
  },
  'zh-CN': {
    code: 'zh-CN',
    name: '简体中文',
    prefix: '/zh',
    hreflang: 'zh-Hans',
    formatLocale: 'zh-CN',
    style: '使用简洁自然的简体中文，保留品牌名与技术字面量。',
    pluralCategories: ['other']
  },
  'ja-JP': {
    code: 'ja-JP',
    name: '日本語',
    prefix: '/ja',
    hreflang: 'ja',
    formatLocale: 'ja-JP',
    style: '自然で簡潔なです・ます体を使い、製品名と技術的な文字列を保持してください。',
    pluralCategories: ['other']
  },
  'es-ES': {
    code: 'es-ES',
    name: 'Español',
    prefix: '/es',
    hreflang: 'es',
    formatLocale: 'es-ES',
    style: 'Usa español internacional neutro, claro y conciso. Conserva las marcas y los literales técnicos.',
    pluralCategories: ['one', 'other']
  },
  'pt-BR': {
    code: 'pt-BR',
    name: 'Português (Brasil)',
    prefix: '/pt',
    hreflang: 'pt-BR',
    formatLocale: 'pt-BR',
    style: 'Use português brasileiro claro e conciso. Preserve marcas e literais técnicos.',
    pluralCategories: ['one', 'other']
  },
  'ru-RU': {
    code: 'ru-RU',
    name: 'Русский',
    prefix: '/ru',
    hreflang: 'ru',
    formatLocale: 'ru-RU',
    style: 'Используйте ясный и краткий русский язык. Сохраняйте названия продуктов и технические литералы.',
    pluralCategories: ['one', 'few', 'many', 'other']
  }
} as const;
